In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.ensemble import IsolationForest
import seaborn as sns
from sklearn.preprocessing import LabelEncoder

In [2]:
milk=pd.read_csv("D:\\AshleshaRuchika\\PGCP-AI\\Machine Learning\\Datasets\\milk.csv",index_col=0)
milk.head(2)

           water  protein  fat  lactose   ash
Animal
HORSE       90.1      2.6  1.0      6.9  0.35
ORANGUTAN   88.5      1.4  3.5      6.0  0.24

In [3]:
clf=IsolationForest(contamination=0.05,random_state=26)
clf.fit(milk)
predictions=clf.predict(milk)
predictions

array([ 1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,
        1,  1,  1,  1,  1,  1, -1, -1])

In [6]:
glass=pd.read_csv("D:\\AshleshaRuchika\\PGCP-AI\\Machine Learning\\Cases (1)\\Glass_Identification\\Glass.csv")
glass.head(5)

,RI,Na,Mg,Al,Si,K,Ca,Ba,Fe,Type
0,1.52101,13.64,4.49,1.10,71.78,0.06,8.75,0.0,0.0,building_windows_float_processed
1,1.51761,13.89,3.60,1.36,72.73,0.48,7.83,0.0,0.0,building_windows_float_processed
2,1.51618,13.53,3.55,1.54,72.99,0.39,7.78,0.0,0.0,building_windows_float_processed
3,1.51766,13.21,3.69,1.29,72.61,0.57,8.22,0.0,0.0,building_windows_float_processed
4,1.51742,13.27,3.62,1.24,73.08,0.55,8.07,0.0,0.0,building_windows_float_processed

In [7]:
df=glass.drop("Type",axis=1)

In [8]:
clf=IsolationForest(contamination=0.05,random_state=26)
clf.fit(df)
predictions=clf.predict(df)
predictions

array([ 1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,
        1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,
        1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,
        1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,
        1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,
        1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,
        1,  1,  1, -1, -1, -1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,
        1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,
        1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,
        1,  1,  1,  1,  1,  1,  1,  1,  1,  1, -1,  1,  1,  1,  1,  1,  1,
        1, -1, -1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1, -1, -1, -1,
        1,  1, -1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,
        1,  1,  1, -1,  1,  1,  1,  1,  1,  1])

In [9]:
df['outlier_status'] = predictions
outliers = df[df['outlier_status'] == -1]
outliers

,RI,Na,Mg,Al,Si,K,Ca,Ba,Fe,outlier_status
105,1.52475,11.45,0.00,1.88,72.19,0.81,13.24,0.00,0.34,-1
106,1.53125,10.73,0.00,2.10,69.81,0.58,13.30,3.15,0.28,-1
107,1.53393,12.30,0.00,1.00,70.16,0.12,16.19,0.00,0.24,-1
163,1.51514,14.01,2.68,3.50,69.89,1.68,5.87,2.20,0.00,-1
171,1.51316,13.02,0.00,3.04,70.48,6.21,6.96,0.00,0.00,-1
172,1.51321,13.00,0.00,3.02,70.70,6.21,6.93,0.00,0.00,-1
184,1.51115,17.38,0.00,0.34,75.41,0.00,6.65,0.00,0.00,-1
185,1.51131,13.69,3.20,1.81,72.81,1.76,5.43,1.19,0.00,-1
186,1.51838,14.32,3.26,2.22,71.25,1.46,5.79,1.63,0.00,-1
189,1.52365,15.79,1.83,1.31,70.43,0.31,8.61,1.68,0.00,-1
207,1.51831,14.39,0.00,1.82,72.86,1.41,6.47,2.88,0.00,-1

In [10]:
count_table = pd.crosstab(glass['Type'], df['outlier_status'],margins=True)
count_table

outlier_status                        -1    1  All
Type
building_windows_float_processed       0   70   70
building_windows_non_float_processed   3   73   76
containers                             3   10   13
headlamps                              4   25   29
tableware                              1    8    9
vehicle_windows_float_processed        0   17   17
All                                   11  203  214

In [11]:
print("percentage of outliers="+str((predictions<0).mean()*100)+"%")

percentage of outliers=5.14018691588785%

In [12]:
from xgboost import XGBClassifier
from sklearn.model_selection import StratifiedKFold,GridSearchCV

In [15]:
in_glass=df[predictions!=-1]
le=LabelEncoder()
kfold=StratifiedKFold(n_splits=5,shuffle=True,random_state=26)
in_glass['Type']=le.fit_transform(in_glass['Type'])
X,y=in_glass.drop('Type',axis=1),in_glass['Type']
params={'learning_rate':np.linspace(0.0001,0.9,30),'n_estimators':[10,25,50,75,100],'max_depth':[2,3,4,5,6]}
gbm=XGBClassifier(random_state=26,n_jobs=-1)
gcv=GridSearchCV(gbm,param_grid=params,cv=kfold,scoring='neg_log_loss')

gcv.fit(X,y)
gcv.best_params_,gcv.best_score_

KeyError: 'Type'