In [1]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder, OneHotEncoder
from sklearn.metrics import accuracy_score, roc_auc_score, log_loss
from sklearn.svm import SVC

In [2]:
sonar=pd.read_csv("D:\\AshleshaRuchika\\PGCP-AI\\Machine Learning\\Sonar\\Sonar.csv")
le=LabelEncoder()
sonar['Class']=le.fit_transform(sonar['Class'])
X,y=sonar.drop('Class',axis=1), sonar['Class']
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.3,random_state=26,stratify=y)

In [3]:
svm=SVC(kernel='linear')
svm.fit(X_train,y_train)
y_pred=svm.predict(X_test)
accuracy_score(y_test,y_pred)

0.8412698412698413

In [4]:
#accuracy score
Cs=np.linspace(0.001,5,20)
scores=[]
for c in Cs:
    svm=SVC(kernel='linear',C=c)
    svm.fit(X_train,y_train)
    y_pred=svm.predict(X_test)
    scores.append([c,accuracy_score(y_test,y_pred)])
df_scores=pd.DataFrame(scores,columns=['C','score'])
df_scores.sort_values('score',ascending=False)

           C     score
3   0.790316  0.841270
6   1.579632  0.841270
5   1.316526  0.841270
4   1.053421  0.841270
15  3.947579  0.825397
7   1.842737  0.825397
2   0.527211  0.809524
12  3.158263  0.809524
11  2.895158  0.809524
8   2.105842  0.809524
10  2.632053  0.809524
9   2.368947  0.809524
16  4.210684  0.809524
14  3.684474  0.809524
13  3.421368  0.809524
1   0.264105  0.793651
18  4.736895  0.793651
17  4.473789  0.793651
19  5.000000  0.793651
0   0.001000  0.539683

In [9]:
svm=SVC(kernel='linear', probability=True, random_state=26)
svm.fit(X_train,y_train)
y_pred_prob=svm.predict_proba(X_test)
log_loss(y_test,y_pred_prob)

0.49100661645035415

In [14]:
#log loss
Cs=np.linspace(0.001,5,20)
scores=[]
for c in Cs:
    svm=SVC(kernel='linear',C=c,probability=True, random_state=26)
    svm.fit(X_train,y_train)
    y_pred_prob=svm.predict_proba(X_test)
    scores.append([c,log_loss(y_test,y_pred_prob)])
df_scores=pd.DataFrame(scores,columns=['C','score'])
df_scores.sort_values('score',ascending=True)

           C     score
3   0.790316  0.488054
4   1.053421  0.493004
8   2.105842  0.495309
7   1.842737  0.495447
6   1.579632  0.496055
9   2.368947  0.497287
5   1.316526  0.497609
2   0.527211  0.498198
10  2.632053  0.500052
1   0.264105  0.504347
11  2.895158  0.505062
13  3.421368  0.507939
12  3.158263  0.508675
14  3.684474  0.509644
15  3.947579  0.511260
16  4.210684  0.513410
17  4.473789  0.514990
18  4.736895  0.516654
19  5.000000  0.517905
0   0.001000  0.693147

## polynomial kernel

In [17]:
#log loss
Cs=np.linspace(0.001,5,20)
Ds=[2,3,4]
scores=[]
for c in Cs:
    for d in Ds:
        svm=SVC(kernel='poly',C=c,probability=True, random_state=26, degree=d)
        svm.fit(X_train,y_train)
        y_pred_prob=svm.predict_proba(X_test)
        scores.append([c,d,log_loss(y_test,y_pred_prob)])
df_scores=pd.DataFrame(scores,columns=['C','dergee','score'])
df_scores.sort_values('score',ascending=True)

           C  dergee     score
59  5.000000       4  0.390880
56  4.736895       4  0.390901
53  4.473789       4  0.391032
50  4.210684       4  0.391403
41  3.421368       4  0.391449
47  3.947579       4  0.391599
44  3.684474       4  0.391740
38  3.158263       4  0.393758
35  2.895158       4  0.395712
32  2.632053       4  0.398660
5   0.264105       4  0.398905
29  2.368947       4  0.402628
26  2.105842       4  0.406395
8   0.527211       4  0.407125
23  1.842737       4  0.407165
20  1.579632       4  0.409386
57  5.000000       2  0.414176
49  4.210684       3  0.414178
52  4.473789       3  0.414916
16  1.316526       3  0.415099
46  3.947579       3  0.415104
54  4.736895       2  0.415776
55  4.736895       3  0.415887
19  1.579632       3  0.416369
58  5.000000       3  0.416828
51  4.473789       2  0.417328
43  3.684474       3  0.417347
17  1.316526       4  0.417598
13  1.053421       3  0.417719
40  3.421368       3  0.418298
22  1.842737       3  0.419064
25  2.105842       3  0.420049
48  4.210684       2  0.420313
37  3.158263       3  0.420503
11  0.790316       4  0.420993
34  2.895158       3  0.421760
31  2.632053       3  0.422181
28  2.368947       3  0.422655
45  3.947579       2  0.422813
10  0.790316       3  0.424507
42  3.684474       2  0.424700
14  1.053421       4  0.427077
39  3.421368       2  0.428672
36  3.158263       2  0.431232
7   0.527211       3  0.432346
33  2.895158       2  0.433266
30  2.632053       2  0.435401
4   0.264105       3  0.438377
27  2.368947       2  0.439448
24  2.105842       2  0.445003
21  1.842737       2  0.453503
12  1.053421       2  0.454343
9   0.790316       2  0.456724
18  1.579632       2  0.456866
15  1.316526       2  0.457814
3   0.264105       2  0.473458
6   0.527211       2  0.474913
0   0.001000       2  0.693147
1   0.001000       3  0.696203
2   0.001000       4  0.698510

## Radial Kernel

In [22]:
Cs=np.linspace(0.001,5,20)
Gs=np.linspace(0.001,5,20)
Ds=[2,3,4]
scores=[]
for c in Cs:
    for g in Gs:
        svm=SVC(kernel='rbf',C=c,probability=True, random_state=26,gamma=g)
        svm.fit(X_train,y_train)
        y_pred_prob=svm.predict_proba(X_test)
        scores.append([c,d,log_loss(y_test,y_pred_prob)])
df_scores=pd.DataFrame(scores,columns=['C','gamma','score'])
df_scores.sort_values('score',ascending=True)

            C  gamma     score
62   0.790316  0.001  0.402014
19   0.001000  0.001  0.402267
23   0.264105  0.001  0.402409
82   1.053421  0.001  0.402949
18   0.001000  0.001  0.403108
..        ...    ...       ...
180  2.368947  0.001  0.693147
380  5.000000  0.001  0.693147
160  2.105842  0.001  0.693147
140  1.842737  0.001  0.693147
1    0.001000  0.001  0.697762

[400 rows x 3 columns]

## sigmoid Kernal

In [23]:
Cs=np.linspace(0.001,5,20)
coef=np.linspace(-5,5,20)
Ds=[2,3,4]
scores=[]
for c in Cs:
    for cf in coef:
        svm=SVC(kernel='sigmoid',C=c,probability=True, random_state=26,coef0=cf)
        svm.fit(X_train,y_train)
        y_pred_prob=svm.predict_proba(X_test)
        scores.append([c,d,log_loss(y_test,y_pred_prob)])
df_scores=pd.DataFrame(scores,columns=['C','coef0','score'])
df_scores.sort_values('score',ascending=True)

            C  coef0     score
53   0.527211  0.001  0.385637
52   0.527211  0.001  0.389071
72   0.790316  0.001  0.389228
71   0.790316  0.001  0.390249
54   0.527211  0.001  0.391220
..        ...    ...       ...
225  2.895158  0.001  0.699668
185  2.368947  0.001  0.699672
165  2.105842  0.001  0.699739
145  1.842737  0.001  0.699829
125  1.579632  0.001  0.699851

[400 rows x 3 columns]