In [6]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer, make_column_selector
from scipy.cluster.hierarchy import dendrogram, linkage
from sklearn.cluster import AgglomerativeClustering
from sklearn.metrics import silhouette_score
from sklearn.cluster import KMeans
from sklearn.preprocessing import StandardScaler
from sklearn.decomposition import PCA

In [2]:
df=pd.read_csv("D:\\AshleshaRuchika\\PGCP-AI\\Machine Learning\\Cases (1)\\Recency Frequency Monetary\\rfm_data_customer.csv",index_col=0)
df

             revenue most_recent_visit  number_of_orders  recency_days
customer_id
22086            777        2006-05-14                 9           232
2290            1555        2006-09-08                16           115
26377            336        2006-11-19                 5            43
24650           1189        2006-10-29                12            64
12883           1229        2006-12-09                12            23
...              ...               ...               ...           ...
3249             998        2006-12-01                10            31
6686             771        2006-06-28                 8           187
16418           1016        2006-07-31                 9           154
9117             678        2006-06-20                 7           195
19184           1519        2006-09-10                13           113

[39999 rows x 4 columns]

In [3]:

res=df.drop("most_recent_visit",axis=1)
res

             revenue  number_of_orders  recency_days
customer_id
22086            777                 9           232
2290            1555                16           115
26377            336                 5            43
24650           1189                12            64
12883           1229                12            23
...              ...               ...           ...
3249             998                10            31
6686             771                 8           187
16418           1016                 9           154
9117             678                 7           195
19184           1519                13           113

[39999 rows x 3 columns]

In [4]:
scaler=StandardScaler().set_output(transform='pandas')
df_scaled=scaler.fit_transform(res)
Ks=[2,3,4,5]
scores=[]
for i in Ks:
    clust=AgglomerativeClustering(n_clusters=i)
    clust.fit(df_scaled)
    scores.append([i,silhouette_score(df_scaled,clust.labels_)])

df_scores=pd.DataFrame(scores,columns=['clusters','score'])
df_scores.sort_values('score',ascending=False)

   clusters     score
1         3  0.346685
0         2  0.341961
2         4  0.282713
3         5  0.274843

In [7]:
prcomp=PCA().set_output(transform="pandas")
df_scaled=scaler.fit_transform(df)
pca_data=prcomp.fit_transform(df_scaled)
km=KMeans(n_clusters=2,random_state=26)
km.fit(df_scaled)
pca_data["Cluster"]=km.labels_
pca_data["Cluster"]=pca_data["Cluster"].astype(str)

ValueError: could not convert string to float: '2006-05-14'

In [ ]:
df1=df.copy()
km=KMeans(n_clusters=5,random_state=26)
km.fit(df_scaled)
df1["Cluster"]=km.labels_
df1.groupby("Cluster").mean()

In [ ]:
df1