In [6]:
import numpy as np
import os
import pandas as pd
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_absolute_error, root_mean_squared_error, r2_score
from sklearn.preprocessing import PolynomialFeatures
from sklearn.impute import SimpleImputer
os.chdir("D:\\AshleshaRuchika\\PGCP-AI\\Machine Learning\\Datasets")

In [7]:
job=pd.read_csv("JobSalary2.csv", index_col="S_No")
job

      Computer  Marketing  Engineer
S_No
1         84.0       55.0        75
2         90.0       53.0        70
3         63.0        NaN        88
4          NaN       50.0        77
5         63.0       41.0        89
6         75.0       54.0        85
7          NaN       51.0        96
8         77.0       64.0       105

In [8]:
job.isnull().sum().sum()

np.int64(3)

In [9]:
const_imp=SimpleImputer(strategy='constant',fill_value=60).set_output(transform='pandas')
const_imp.fit_transform(job)

      Computer  Marketing  Engineer
S_No
1         84.0       55.0      75.0
2         90.0       53.0      70.0
3         63.0       60.0      88.0
4         60.0       50.0      77.0
5         63.0       41.0      89.0
6         75.0       54.0      85.0
7         60.0       51.0      96.0
8         77.0       64.0     105.0

In [10]:
mean_imp=SimpleImputer(strategy='mean').set_output(transform='pandas')
mean_imp.fit(job)
mean_imp.statistics_

array([75.33333333, 52.57142857, 85.625     ])

In [11]:
mean_imp.transform(job)

       Computer  Marketing  Engineer
S_No
1     84.000000  55.000000      75.0
2     90.000000  53.000000      70.0
3     63.000000  52.571429      88.0
4     75.333333  50.000000      77.0
5     63.000000  41.000000      89.0
6     75.000000  54.000000      85.0
7     75.333333  51.000000      96.0
8     77.000000  64.000000     105.0