In [3]:
import numpy as np
import pandas as pd

In [11]:
#data
companies= np.array(["TCS","Infosys","Wipro"])
sales= np.array([100,300,200])
profit=np.array([40.80,30,55])
print("------Numpy Arrays------------")
print("companies:",companies)
print("sales:",sales)
print("profit:",profit)

------Numpy Arrays------------
companies: ['TCS' 'Infosys' 'Wipro']
sales: [100 300 200]
profit: [40.8 30.  55. ]

In [12]:
#Access using index
print("\nUsing numpy:")
print("Infosys sales:",sales[1])
print("Infosys profit:",profit[1])

Using numpy:
Infosys sales: 300
Infosys profit: 30.0

In [13]:
#pandas series
sales_s= pd.Series(sales,index=companies)
profit_s=pd.Series(profit,index=companies)

In [14]:
print("\n\n--------pandas series-----------")
print("sales series:\n",sales_s)
print("\nprofit series:\n",profit_s)

--------pandas series-----------
sales series:
 TCS        100
Infosys    300
Wipro      200
dtype: int64

profit series:
 TCS        40.8
Infosys    30.0
Wipro      55.0
dtype: float64

In [15]:
#access using label
print("\nUsing series:")
print("Infosys sales:",sales_s["Infosys"])
print("Infosys profit:",profit_s["Infosys"])

Using series:
Infosys sales: 300
Infosys profit: 30.0

In [16]:
#Exercise :we want to store student PRN ,name,mobile no for 3 students.
# use numpy arrays and then pandas series.print 3rd studnets name and 2nd students moblie no
student_prn=np.array([100,1,5])
student_name=np.array(["Ruchika","Ashlesha","Priti"])
student_mb= np.array([1234,4677,7654])
print("Student_prn:",student_prn)
print("Student_name:",student_name)
print("Student_mb:",student_mb)

Student_prn: [100   1   5]
Student_name: ['Ruchika' 'Ashlesha' 'Priti']
Student_mb: [1234 4677 7654]

In [18]:
#Access using index
print("\nUsing numpy:")
print("3rd Students Name:",student_name[2])
print("2nd students moblie no:",student_mb[1])

Using numpy:
3rd Students Name: Priti
2nd students moblie no: 4677

In [21]:
name_s=pd.Series(student_name,index=student_prn)
mobile_s=pd.Series(student_mb,index=student_prn)
print("\n\n--------pandas series-----------")
print("\nname series:\n",name_s)
print("\nmobile series:\n",mobile_s)

--------pandas series-----------

name series:
 100     Ruchika
1      Ashlesha
5         Priti
dtype: str

mobile series:
 100    1234
1      4677
5      7654
dtype: int64

In [20]:
#access using label
print("\nUsing series:")
print("3rd Students Name:",name_s[5 ])
print("2nd students moblie no:",mobile_s[1])

Using series:
3rd Students Name: Priti
2nd students moblie no: 4677

In [24]:
#DataFrame
df= pd.DataFrame({"Student Name":student_name,"MB no":student_mb},index=student_prn)
print(df)

    Student Name  MB no
100      Ruchika   1234
1       Ashlesha   4677
5          Priti   7654

In [25]:
#Access row and multiple colums
print("\nUsing DataFrame:")
print(df.loc[100,["Student Name","MB no"]])

Using DataFrame:
Student Name    Ruchika
MB no              1234
Name: 100, dtype: object

In [27]:
#Add new column
df["Marks"]=df["MB no"]*2
print(df)

    Student Name  MB no  Marks
100      Ruchika   1234   2468
1       Ashlesha   4677   9354
5          Priti   7654  15308

In [29]:
#filter multiple columns
print("\nHigh Marks:\n",df[df["Marks"]>4000])

High Marks:
   Student Name  MB no  Marks
1     Ashlesha   4677   9354
5        Priti   7654  15308

In [32]:
data={
    "Player":["Virat","Rohit","Dhoni"],
    "Match 1":[45, 67 ,87],
    "Match 2":[10, 60 ,50],
    "Match 3":[20, 40 ,80],
}
df1=pd.DataFrame(data).set_index("Player")
print("DataFrame:\n",df1)

DataFrame:
         Match 1  Match 2  Match 3
Player
Virat        45       10       20
Rohit        67       60       40
Dhoni        87       50       80

In [34]:
#First row
print("\nFirst row:")
print("loc:",df1.loc["Virat"].values)
print("iloc:",df1.iloc[0].values)

First row:
loc: [45 10 20]
iloc: [45 10 20]

In [35]:
#Second Row
print("\nSecond  row:")
print("loc:",df1.loc["Rohit"].values)
print("iloc:",df1.iloc[1].values)

Second  row:
loc: [67 60 40]
iloc: [67 60 40]

In [36]:
#Third row
print("\nThird  row:")
print("loc:",df1.loc["Dhoni"].values)
print("iloc:",df1.iloc[2].values)

Third  row:
loc: [87 50 80]
iloc: [87 50 80]

In [46]:
#Multiple row
print("\nMultiple rows:")
print("loc:",df1.loc[["Virat","Rohit"]])
print("iloc:",df1.iloc[0:2])

Multiple rows:
loc:         Match 1  Match 2  Match 3
Player
Virat        45       10       20
Rohit        67       60       40
iloc:         Match 1  Match 2  Match 3
Player
Virat        45       10       20
Rohit        67       60       40

In [40]:
#Specific cell
print("\nSpecific cell(Virat,Match 2):")
print("loc:",df1.loc["Virat","Match 2"])
print("iloc:",df1.iloc[0:1])

Specific cell(Virat,Match 2):
loc: 10
iloc:         Match 1  Match 2  Match 3
Player
Virat        45       10       20

In [42]:
#Subset
print("\nSubset:")
print("loc:\n",df.loc[["Virat","Dhoni"],["Match 1","Match 2"]])

Subset:
loc:
         Match 1  Match 2
Player
Virat        45       10
Dhoni        87       50

In [44]:
#Slicing
print("\nSlicing:")
print("loc:\n",df.loc["Virat":"Dhoni"])
print("iloc:\n",df.iloc[0:2])

Slicing:
loc:
         Match 1  Match 2  Match 3
Player
Virat        45       10       20
Rohit        67       60       40
Dhoni        87       50       80
iloc:
         Match 1  Match 2  Match 3
Player
Virat        45       10       20
Rohit        67       60       40

In [99]:
df2= pd.DataFrame({
    "Employee":["Amit","Neha","Amey","Rohit","Raj"],
    "Department":["IT","HR","IT","Finance",np.nan],
    "Salary":[10000,70000,45000,76500,0]})
# print(df2)
df2

  Employee Department  Salary
0     Amit         IT   10000
1     Neha         HR   70000
2     Amey         IT   45000
3    Rohit    Finance   76500
4      Raj        NaN       0

In [100]:
#Indexing
df2_Indexed=df2.set_index("Employee")
# print("\n Set Employee as index:\n",df2_Indexed)
df2_Indexed

         Department  Salary
Employee
Amit             IT   10000
Neha             HR   70000
Amey             IT   45000
Rohit       Finance   76500
Raj             NaN       0

In [101]:
#Filtering
# print("\nSalary>50000:\n",df2[df2["Salary"]>50000])
df2[df2["Salary"]>50000]

  Employee Department  Salary
1     Neha         HR   70000
3    Rohit    Finance   76500

In [102]:
#check missing
# print("\nMissing Values:\n",df2.isnull())
df2.isnull()

   Employee  Department  Salary
0     False       False   False
1     False       False   False
2     False       False   False
3     False       False   False
4     False        True   False

In [103]:
#fill missing
print("\nFill misiing with:\n",df2.fillna(0))

Fill misiing with:
   Employee Department  Salary
0     Amit         IT   10000
1     Neha         HR   70000
2     Amey         IT   45000
3    Rohit    Finance   76500
4      Raj          0       0

In [104]:
#Drop misiing
print("\n Drop missing rows:\n",df2.dropna())

 Drop missing rows:
   Employee Department  Salary
0     Amit         IT   10000
1     Neha         HR   70000
2     Amey         IT   45000
3    Rohit    Finance   76500

In [74]:
# Grouping
print("\n Average Salary by Department:\n",df2.groupby("Department")["Salary"].mean())

 Average Salary by Department:
 Department
Business    76500.0
Finance     56780.0
HR          70000.0
IT          27500.0
Name: Salary, dtype: float64

In [108]:
#Merge(join)
df2_bonus=pd.DataFrame({
    "Employee":["Amit","Neha","Raj"],
    "Bonus":[5000,8000,5000]})

merged=pd.merge(df2,df2_bonus,on="Employee")
# print("\nMerged DataFrame:\n",merged)
merged

  Employee Department  Salary  Bonus
0     Amit         IT   10000   5000
1     Neha         HR   70000   8000
2      Raj        NaN       0   5000

In [109]:
#concat
df2_new= pd.DataFrame({
    "Employee":["Kiran"],
    "Department":["IT"],
    "Salary":[50000]})
concat_df2=pd.concat([df2,df2_new],ignore_index=True)
# print("\n Concatenated DataFrame:\n",concat_df2)
concat_df2

  Employee Department  Salary
0     Amit         IT   10000
1     Neha         HR   70000
2     Amey         IT   45000
3    Rohit    Finance   76500
4      Raj        NaN       0
5    Kiran         IT   50000