In [1]:
# SL-Assignment-3
# Name: Ashlesha Tayade                        Name: Ruchika Gaikwad
# PRN: 260240128008                            PRN: 260240128036

In [2]:
import pandas as pd
import numpy as np
import seaborn as sns

In [3]:
# 1. Load the tips dataset into a DataFrame.
df=sns.load_dataset("tips")
df

     total_bill   tip     sex smoker   day    time  size
0         16.99  1.01  Female     No   Sun  Dinner     2
1         10.34  1.66    Male     No   Sun  Dinner     3
2         21.01  3.50    Male     No   Sun  Dinner     3
3         23.68  3.31    Male     No   Sun  Dinner     2
4         24.59  3.61  Female     No   Sun  Dinner     4
..          ...   ...     ...    ...   ...     ...   ...
239       29.03  5.92    Male     No   Sat  Dinner     3
240       27.18  2.00  Female    Yes   Sat  Dinner     2
241       22.67  2.00    Male    Yes   Sat  Dinner     2
242       17.82  1.75    Male     No   Sat  Dinner     2
243       18.78  3.00  Female     No  Thur  Dinner     2

[244 rows x 7 columns]

In [4]:
# 2. Display the first 5 rows of the tips dataset.
df.head()

   total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4

In [5]:
# 3. Show all column names in the tips dataset.
df.columns

Index(['total_bill', 'tip', 'sex', 'smoker', 'day', 'time', 'size'], dtype='str')

In [6]:
# 4. Find the average total_bill.
df["total_bill"].mean()

np.float64(19.78594262295082)

In [7]:
# 5. Find the maximum tip given.
df["tip"].max()

np.float64(10.0)

In [8]:
# 6. Filter all rows where total_bill is greater than 20.
filt=df["total_bill"]>20
df.loc[filt,:]

     total_bill   tip     sex smoker  day    time  size
2         21.01  3.50    Male     No  Sun  Dinner     3
3         23.68  3.31    Male     No  Sun  Dinner     2
4         24.59  3.61  Female     No  Sun  Dinner     4
5         25.29  4.71    Male     No  Sun  Dinner     4
7         26.88  3.12    Male     No  Sun  Dinner     4
..          ...   ...     ...    ...  ...     ...   ...
237       32.83  1.17    Male    Yes  Sat  Dinner     2
238       35.83  4.67  Female     No  Sat  Dinner     3
239       29.03  5.92    Male     No  Sat  Dinner     3
240       27.18  2.00  Female    Yes  Sat  Dinner     2
241       22.67  2.00    Male    Yes  Sat  Dinner     2

[97 rows x 7 columns]

In [9]:
# 7. Filter all rows where smoker is Yes.
filt=df["smoker"]=="Yes"
df.loc[filt,:]

     total_bill   tip     sex smoker  day    time  size
56        38.01  3.00    Male    Yes  Sat  Dinner     4
58        11.24  1.76    Male    Yes  Sat  Dinner     2
60        20.29  3.21    Male    Yes  Sat  Dinner     2
61        13.81  2.00    Male    Yes  Sat  Dinner     2
62        11.02  1.98    Male    Yes  Sat  Dinner     2
..          ...   ...     ...    ...  ...     ...   ...
234       15.53  3.00    Male    Yes  Sat  Dinner     2
236       12.60  1.00    Male    Yes  Sat  Dinner     2
237       32.83  1.17    Male    Yes  Sat  Dinner     2
240       27.18  2.00  Female    Yes  Sat  Dinner     2
241       22.67  2.00    Male    Yes  Sat  Dinner     2

[93 rows x 7 columns]

In [10]:
# 8. Show only total_bill, tip, and day columns.
df[["total_bill","tip","day"]]

     total_bill   tip   day
0         16.99  1.01   Sun
1         10.34  1.66   Sun
2         21.01  3.50   Sun
3         23.68  3.31   Sun
4         24.59  3.61   Sun
..          ...   ...   ...
239       29.03  5.92   Sat
240       27.18  2.00   Sat
241       22.67  2.00   Sat
242       17.82  1.75   Sat
243       18.78  3.00  Thur

[244 rows x 3 columns]

In [11]:
# 9. Find the average tip grouped by day.
df.groupby("day")["tip"].mean()

day
Thur    2.771452
Fri     2.734737
Sat     2.993103
Sun     3.255132
Name: tip, dtype: float64

In [12]:
# 10. Find the average total_bill grouped by time.
df.groupby("time")["total_bill"].mean()

time
Lunch     17.168676
Dinner    20.797159
Name: total_bill, dtype: float64

In [13]:
# 11. Count how many records belong to each day.
df["day"].value_counts()

day
Sat     87
Sun     76
Thur    62
Fri     19
Name: count, dtype: int64

In [26]:
# 12. Count how many smokers and non-smokers are present.
df["smoker"].value_counts()

smoker
No     151
Yes     93
Name: count, dtype: int64

In [27]:
# 13. Find the total tip collected on each day.
df.groupby("day")["tip"].sum()

day
Thur    171.83
Fri      51.96
Sat     260.40
Sun     247.39
Name: tip, dtype: float64

In [28]:
# 14. Find the average tip for lunch and dinner separately.
df.groupby("time")["tip"].mean()

time
Lunch     2.728088
Dinner    3.102670
Name: tip, dtype: float64

In [30]:
# 15. Create a new column tip_percent = (tip / total_bill) * 100.
df["tip_percent"]=(df["tip"]/df["total_bill"])*100
df

     total_bill   tip     sex smoker   day    time  size  tip_percent
0         16.99  1.01  Female     No   Sun  Dinner     2     5.944673
1         10.34  1.66    Male     No   Sun  Dinner     3    16.054159
2         21.01  3.50    Male     No   Sun  Dinner     3    16.658734
3         23.68  3.31    Male     No   Sun  Dinner     2    13.978041
4         24.59  3.61  Female     No   Sun  Dinner     4    14.680765
..          ...   ...     ...    ...   ...     ...   ...          ...
239       29.03  5.92    Male     No   Sat  Dinner     3    20.392697
240       27.18  2.00  Female    Yes   Sat  Dinner     2     7.358352
241       22.67  2.00    Male    Yes   Sat  Dinner     2     8.822232
242       17.82  1.75    Male     No   Sat  Dinner     2     9.820426
243       18.78  3.00  Female     No  Thur  Dinner     2    15.974441

[244 rows x 8 columns]

In [33]:
# 16. Find the row with the highest tip_percent.
filt=df["tip_percent"].idxmax()
df.loc[filt,:]

total_bill          7.25
tip                 5.15
sex                 Male
smoker               Yes
day                  Sun
time              Dinner
size                   2
tip_percent    71.034483
Name: 172, dtype: object

In [34]:
# 17. Find the average size of dining group by day.
df["day"].value_counts()

day
Sat     87
Sun     76
Thur    62
Fri     19
Name: count, dtype: int64

In [35]:
# 18. Sort the tips dataset by tip in descending order.
df.sort_values(by="tip",ascending=False)

     total_bill    tip     sex smoker   day    time  size  tip_percent
170       50.81  10.00    Male    Yes   Sat  Dinner     3    19.681165
212       48.33   9.00    Male     No   Sat  Dinner     4    18.621974
23        39.42   7.58    Male     No   Sat  Dinner     4    19.228818
59        48.27   6.73    Male     No   Sat  Dinner     4    13.942407
141       34.30   6.70    Male     No  Thur   Lunch     6    19.533528
..          ...    ...     ...    ...   ...     ...   ...          ...
0         16.99   1.01  Female     No   Sun  Dinner     2     5.944673
111        7.25   1.00  Female     No   Sat  Dinner     1    13.793103
92         5.75   1.00  Female    Yes   Fri  Dinner     2    17.391304
67         3.07   1.00  Female    Yes   Sat  Dinner     1    32.573290
236       12.60   1.00    Male    Yes   Sat  Dinner     2     7.936508

[244 rows x 8 columns]

In [36]:
# 19. Filter records where size is greater than or equal to 4.
filt=df["size"]>=4
df.loc[filt,:]

     total_bill   tip     sex smoker   day    time  size  tip_percent
4         24.59  3.61  Female     No   Sun  Dinner     4    14.680765
5         25.29  4.71    Male     No   Sun  Dinner     4    18.623962
7         26.88  3.12    Male     No   Sun  Dinner     4    11.607143
11        35.26  5.00  Female     No   Sun  Dinner     4    14.180374
13        18.43  3.00    Male     No   Sun  Dinner     4    16.277808
23        39.42  7.58    Male     No   Sat  Dinner     4    19.228818
25        17.81  2.34    Male     No   Sat  Dinner     4    13.138686
31        18.35  2.50    Male     No   Sat  Dinner     4    13.623978
33        20.69  2.45  Female     No   Sat  Dinner     4    11.841469
44        30.40  5.60    Male     No   Sun  Dinner     4    18.421053
47        32.40  6.00    Male     No   Sun  Dinner     4    18.518519
52        34.81  5.20  Female     No   Sun  Dinner     4    14.938236
54        25.56  4.34    Male     No   Sun  Dinner     4    16.979656
56        38.01  3.00    Male    Yes   Sat  Dinner     4     7.892660
59        48.27  6.73    Male     No   Sat  Dinner     4    13.942407
63        18.29  3.76    Male    Yes   Sat  Dinner     4    20.557682
77        27.20  4.00    Male     No  Thur   Lunch     4    14.705882
85        34.83  5.17  Female     No  Thur   Lunch     4    14.843526
95        40.17  4.73    Male    Yes   Fri  Dinner     4    11.774956
116       29.93  5.07    Male     No   Sun  Dinner     4    16.939526
119       24.08  2.92  Female     No  Thur   Lunch     4    12.126246
125       29.80  4.20  Female     No  Thur   Lunch     6    14.093960
141       34.30  6.70    Male     No  Thur   Lunch     6    19.533528
142       41.19  5.00    Male     No  Thur   Lunch     5    12.138869
143       27.05  5.00  Female     No  Thur   Lunch     6    18.484288
153       24.55  2.00    Male     No   Sun  Dinner     4     8.146640
154       19.77  2.00    Male     No   Sun  Dinner     4    10.116338
155       29.85  5.14  Female     No   Sun  Dinner     5    17.219430
156       48.17  5.00    Male     No   Sun  Dinner     6    10.379905
157       25.00  3.75  Female     No   Sun  Dinner     4    15.000000
159       16.49  2.00    Male     No   Sun  Dinner     4    12.128563
160       21.50  3.50    Male     No   Sun  Dinner     4    16.279070
167       31.71  4.50    Male     No   Sun  Dinner     4    14.191107
180       34.65  3.68    Male    Yes   Sun  Dinner     4    10.620491
183       23.17  6.50    Male    Yes   Sun  Dinner     4    28.053517
185       20.69  5.00    Male     No   Sun  Dinner     5    24.166264
187       30.46  2.00    Male    Yes   Sun  Dinner     5     6.565988
197       43.11  5.00  Female    Yes  Thur   Lunch     4    11.598237
204       20.53  4.00    Male    Yes  Thur   Lunch     4    19.483682
207       38.73  3.00    Male    Yes   Sat  Dinner     4     7.745933
211       25.89  5.16    Male    Yes   Sat  Dinner     4    19.930475
212       48.33  9.00    Male     No   Sat  Dinner     4    18.621974
216       28.15  3.00    Male    Yes   Sat  Dinner     5    10.657194
219       30.14  3.09  Female    Yes   Sat  Dinner     4    10.252157
227       20.45  3.00    Male     No   Sat  Dinner     4    14.669927
230       24.01  2.00    Male    Yes   Sat  Dinner     4     8.329863

In [40]:
# 20. Find the average tip_percent for smokers vs non-smokers.
df.groupby("smoker")["tip_percent"].mean()

smoker
Yes    16.319604
No     15.932846
Name: tip_percent, dtype: float64