In [1]:
# Assignment-5
# Name: Ashlesha Tayade                        Name: Ruchika Gaikwad
# PRN: 260240128008                            PRN: 260240128036

In [2]:
import pandas as pd
import numpy as np

In [3]:
# 1. Create a Series of 5 student names.
name=pd.Series(["Anil","Ruchika","Ramesh","Umesh","Ashlesha"])
name

0        Anil
1     Ruchika
2      Ramesh
3       Umesh
4    Ashlesha
dtype: str

In [4]:
# 2. Create a Series of 5 marks and display it.
marks=pd.Series([50,75,83,60,98])
marks

0    50
1    75
2    83
3    60
4    98
dtype: int64

In [5]:
# 3. Create a Series with custom index labels like A, B, C, D.
data = [10, 20, 30, 40,74,123,66,33,77,234,88,11,np.nan]   
labels = ['A', 'B', 'C', 'D','E','F','G','H','I','J','K','L','M'] 

series = pd.Series(data, index=labels)
series

A     10.0
B     20.0
C     30.0
D     40.0
E     74.0
F    123.0
G     66.0
H     33.0
I     77.0
J    234.0
K     88.0
L     11.0
M      NaN
dtype: float64

In [6]:
# 4. Access the third value from a Series.
series.iloc[3:4]

D    40.0
dtype: float64

In [7]:
# 5. Access a value from a Series using its custom label.
series.loc['A':'D']

A    10.0
B    20.0
C    30.0
D    40.0
dtype: float64

In [8]:
# 6. Change one value in a Series.
series.loc['A']=50
series

A     50.0
B     20.0
C     30.0
D     40.0
E     74.0
F    123.0
G     66.0
H     33.0
I     77.0
J    234.0
K     88.0
L     11.0
M      NaN
dtype: float64

In [9]:
# 7. Add 10 to every value in a numeric Series.
newSeries=series+10
newSeries

A     60.0
B     30.0
C     40.0
D     50.0
E     84.0
F    133.0
G     76.0
H     43.0
I     87.0
J    244.0
K     98.0
L     21.0
M      NaN
dtype: float64

In [10]:
# 8. Find the maximum value in a Series.
series.max()

np.float64(234.0)

In [11]:
# 9. Find the minimum value in a Series.
series.min()

np.float64(11.0)

In [12]:
# 10. Find the mean of a numeric Series.
series.mean()

np.float64(70.5)

In [13]:
# 11. Filter only values greater than 50 in a Series.
series[series>50]

E     74.0
F    123.0
G     66.0
I     77.0
J    234.0
K     88.0
dtype: float64

In [14]:
# 12. Create a Series from a dictionary.
dict1={"One":1,"Two":2,"Three":3}
sr=pd.Series(dict1)
sr

One      1
Two      2
Three    3
dtype: int64

In [15]:
# 13. Check the index of a Series.
series.index

Index(['A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J', 'K', 'L', 'M'], dtype='str')

In [16]:
# 14. Check the values of a Series.
series.values

array([ 50.,  20.,  30.,  40.,  74., 123.,  66.,  33.,  77., 234.,  88.,
        11.,  nan])

In [17]:
# 15. Convert a Series into a list.
list(series)

[50.0, 20.0, 30.0, 40.0, 74.0, 123.0, 66.0, 33.0, 77.0, 234.0, 88.0, 11.0, nan]

In [18]:
# 16. Check which values in a Series are null.
series.isnull()

A    False
B    False
C    False
D    False
E    False
F    False
G    False
H    False
I    False
J    False
K    False
L    False
M     True
dtype: bool

In [19]:
# 17. Fill missing values in a Series with 0.
series.fillna(0)

A     50.0
B     20.0
C     30.0
D     40.0
E     74.0
F    123.0
G     66.0
H     33.0
I     77.0
J    234.0
K     88.0
L     11.0
M      0.0
dtype: float64

In [20]:
# 18. Count how many times each value appears in a Series.
series.value_counts()

50.0     1
20.0     1
30.0     1
40.0     1
74.0     1
123.0    1
66.0     1
33.0     1
77.0     1
234.0    1
88.0     1
11.0     1
Name: count, dtype: int64

In [21]:
# 19. Sort a Series by values.
series.sort_values()

L     11.0
B     20.0
C     30.0
H     33.0
D     40.0
A     50.0
G     66.0
E     74.0
I     77.0
K     88.0
F    123.0
J    234.0
M      NaN
dtype: float64

In [22]:
# 20. Sort a Series by index.
series.sort_index()

A     50.0
B     20.0
C     30.0
D     40.0
E     74.0
F    123.0
G     66.0
H     33.0
I     77.0
J    234.0
K     88.0
L     11.0
M      NaN
dtype: float64

In [23]:
# 21. Create a DataFrame of 5 students with columns Name, Age, Marks.
data=pd.DataFrame({"Name": ["Ashlesha","Ruchika","Sai","Priti","Vijay"],
                  "Age": [25,22,24,25,23],
                  "Marks": [77,57,np.nan,88,43]})
data

       Name  Age  Marks
0  Ashlesha   25   77.0
1   Ruchika   22   57.0
2       Sai   24    NaN
3     Priti   25   88.0
4     Vijay   23   43.0

In [24]:
# 22. Display the first 3 rows of a DataFrame.
data.head(3)

       Name  Age  Marks
0  Ashlesha   25   77.0
1   Ruchika   22   57.0
2       Sai   24    NaN

In [25]:
# 23. Display the last 2 rows of a DataFrame.
data.tail(2)

    Name  Age  Marks
3  Priti   25   88.0
4  Vijay   23   43.0

In [26]:
# 24. Display only one column from a DataFrame.
data["Name"]

0    Ashlesha
1     Ruchika
2         Sai
3       Priti
4       Vijay
Name: Name, dtype: str

In [27]:
# 25. Display two columns from a DataFrame.
data.loc[:,"Name":"Age"]

       Name  Age
0  Ashlesha   25
1   Ruchika   22
2       Sai   24
3     Priti   25
4     Vijay   23

In [28]:
# 26. Add a new column called Passed based on Marks > 40.
data['Passed'] = data['Marks'] > 40
data

       Name  Age  Marks  Passed
0  Ashlesha   25   77.0    True
1   Ruchika   22   57.0    True
2       Sai   24    NaN   False
3     Priti   25   88.0    True
4     Vijay   23   43.0    True

In [29]:
# 27. Add a new column called Bonus with fixed value 5.
data["Bonus"]=5
data

       Name  Age  Marks  Passed  Bonus
0  Ashlesha   25   77.0    True      5
1   Ruchika   22   57.0    True      5
2       Sai   24    NaN   False      5
3     Priti   25   88.0    True      5
4     Vijay   23   43.0    True      5

In [30]:
# 28. Change the values of one existing column.
data["Bonus"]=data["Bonus"]*10
data

       Name  Age  Marks  Passed  Bonus
0  Ashlesha   25   77.0    True     50
1   Ruchika   22   57.0    True     50
2       Sai   24    NaN   False     50
3     Priti   25   88.0    True     50
4     Vijay   23   43.0    True     50

In [31]:
# 29. Delete one column from a DataFrame.
data= data.drop('Bonus', axis=1)
data

       Name  Age  Marks  Passed
0  Ashlesha   25   77.0    True
1   Ruchika   22   57.0    True
2       Sai   24    NaN   False
3     Priti   25   88.0    True
4     Vijay   23   43.0    True

In [32]:
# 30. Rename a column in a DataFrame.
data = data.rename(columns={'Marks': 'Score'})
data

       Name  Age  Score  Passed
0  Ashlesha   25   77.0    True
1   Ruchika   22   57.0    True
2       Sai   24    NaN   False
3     Priti   25   88.0    True
4     Vijay   23   43.0    True

In [33]:
# 31. Set Name as index of the DataFrame.
data.set_index("Name")

          Age  Score  Passed
Name
Ashlesha   25   77.0    True
Ruchika    22   57.0    True
Sai        24    NaN   False
Priti      25   88.0    True
Vijay      23   43.0    True

In [34]:
# 32. Reset the index back to default integers.
data.reset_index(drop=True)

       Name  Age  Score  Passed
0  Ashlesha   25   77.0    True
1   Ruchika   22   57.0    True
2       Sai   24    NaN   False
3     Priti   25   88.0    True
4     Vijay   23   43.0    True

In [35]:
# 33. Select the first row using iloc.
newRow=data.iloc[0]
newRow

Name      Ashlesha
Age             25
Score         77.0
Passed        True
Name: 0, dtype: object

In [36]:
# 34. Select a row using loc with label index.
data.loc[:,"Name":"Passed"]

       Name  Age  Score  Passed
0  Ashlesha   25   77.0    True
1   Ruchika   22   57.0    True
2       Sai   24    NaN   False
3     Priti   25   88.0    True
4     Vijay   23   43.0    True

In [37]:
# 35. Filter students with Marks greater than 60.
data[data["Score"]>60]

       Name  Age  Score  Passed
0  Ashlesha   25   77.0    True
3     Priti   25   88.0    True

In [38]:
# 36. Filter students whose Age is less than 20.
data[data["Age"]<20]

Empty DataFrame
Columns: [Name, Age, Score, Passed]
Index: []

In [39]:
# 37. Find the average Marks of all students.
data["Score"].mean()

np.float64(66.25)

In [40]:
# 38. Find the student with highest Marks.
data["Score"].max()

np.float64(88.0)

In [41]:
# 39. Sort the DataFrame by Marks in ascending order.
data.sort_values(by="Score")

       Name  Age  Score  Passed
4     Vijay   23   43.0    True
1   Ruchika   22   57.0    True
0  Ashlesha   25   77.0    True
3     Priti   25   88.0    True
2       Sai   24    NaN   False

In [42]:
# 40. Sort the DataFrame by Age in descending order
data.sort_values(by="Age",ascending=False)

       Name  Age  Score  Passed
0  Ashlesha   25   77.0    True
3     Priti   25   88.0    True
2       Sai   24    NaN   False
4     Vijay   23   43.0    True
1   Ruchika   22   57.0    True

In [43]:
# 41. Check DataFrame shape.
data.shape

(5, 4)

In [44]:
# 42. Check DataFrame column names.
data.columns

Index(['Name', 'Age', 'Score', 'Passed'], dtype='str')

In [45]:
# 43. Check DataFrame data types.
data.dtypes

Name          str
Age         int64
Score     float64
Passed       bool
dtype: object

In [46]:
# 44. Check if any values are missing in the DataFrame.
data.isnull()

    Name    Age  Score  Passed
0  False  False  False   False
1  False  False  False   False
2  False  False   True   False
3  False  False  False   False
4  False  False  False   False

In [47]:
# 45. Fill missing values in Marks with the column mean.
data["Score"].fillna(data["Score"].mean())

0    77.00
1    57.00
2    66.25
3    88.00
4    43.00
Name: Score, dtype: float64

In [48]:
# 46. Drop rows containing missing values.
data.dropna()

       Name  Age  Score  Passed
0  Ashlesha   25   77.0    True
1   Ruchika   22   57.0    True
3     Priti   25   88.0    True
4     Vijay   23   43.0    True

In [49]:
# 47. Count unique values in a column.
data.nunique()

Name      5
Age       4
Score     4
Passed    2
dtype: int64

In [50]:
# 48. Find value counts of a categorical column like Department.
emp=pd.DataFrame({"Name": ["Ashlesha","Ruchika","Sai","Priti","Vijay"],
                  "Dept": ["IT","Finance","IT","HR","Support"],
                  "Salary": [77000,57464,np.nan,88000,430000]})
print("Employee:",emp)
emp["Dept"].value_counts()

Employee:        Name     Dept    Salary
0  Ashlesha       IT   77000.0
1   Ruchika  Finance   57464.0
2       Sai       IT       NaN
3     Priti       HR   88000.0
4     Vijay  Support  430000.0

Dept
IT         2
Finance    1
HR         1
Support    1
Name: count, dtype: int64

In [51]:
# 49. Create a second DataFrame and concatenate it with the first one.
emp1=pd.DataFrame({"Name": ["Prachi","Ashish","Pranita"],
                  "Dept": ["IT","Finance","Support"],
                  "Salary": [77000,57464,430000]})
print(emp1)
pd.concat([emp,emp1],ignore_index=True)

      Name     Dept  Salary
0   Prachi       IT   77000
1   Ashish  Finance   57464
2  Pranita  Support  430000

       Name     Dept    Salary
0  Ashlesha       IT   77000.0
1   Ruchika  Finance   57464.0
2       Sai       IT       NaN
3     Priti       HR   88000.0
4     Vijay  Support  430000.0
5    Prachi       IT   77000.0
6    Ashish  Finance   57464.0
7   Pranita  Support  430000.0

In [52]:
# 50. Create two DataFrames with a common column and merge them.
emp2=pd.DataFrame({"Name": ["Pratiksha","Ruchika"],
                  "Dept": ["IT","Support"]})
pd.merge(emp,emp2,on="Name",how="outer")

        Name   Dept_x    Salary   Dept_y
0   Ashlesha       IT   77000.0      NaN
1  Pratiksha      NaN       NaN       IT
2      Priti       HR   88000.0      NaN
3    Ruchika  Finance   57464.0  Support
4        Sai       IT       NaN      NaN
5      Vijay  Support  430000.0      NaN