In [1]:
from pathlib import Path
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.preprocessing import StandardScaler, LabelEncoder
from sklearn.model_selection import train_test_split  # for train-test splitting
from sklearn.metrics import (accuracy_score,
                            classification_report,
                            confusion_matrix,
                            f1_score,ConfusionMatrixDisplay)
from collections.abc import Callable
from typing import Literal
import torch
import torch.nn as nn
from torch.utils.data import Dataset, DataLoader
from torchsummary import summary

In [2]:
###----------------------
### Some basic parameters
###----------------------

inpDir = Path('..') / '..' / 'input'
outDir = Path('..') / 'output'
modelDir = Path('..') / 'models'
subDir = 'fifa_2019'

RANDOM_STATE = 24 # for initialization ----- REMEMBER: to remove at the time of promotion to production
np.random.seed(RANDOM_STATE)
rng = np.random.default_rng(seed = RANDOM_STATE) # Set Random Seed for reproducible  results

EPOCHS = 101 # number of epochs
BATCH_SIZE = 32
ALPHA = 0.001 # learning rate
TEST_SIZE = 0.2
TRAIN_SIZE=453*BATCH_SIZE

# parameters for Matplotlib
params = {'legend.fontsize': 'medium',
          'figure.figsize': (15, 6),
          'axes.labelsize': 'medium',
          'axes.titlesize':'large',
          'xtick.labelsize':'medium',
          'ytick.labelsize':'medium'
         }

plt.rcParams.update(params)

CMAP = plt.cm.coolwarm
plt.style.use('seaborn-v0_8-darkgrid') # plt.style.use('ggplot')

In [3]:
# Check if all directories are present
outDir.mkdir(parents=True, exist_ok=True)

modelSubDir = modelDir/ subDir
modelSubDir.mkdir(parents=True, exist_ok=True)

In [4]:
data_df = pd.read_csv('fifa_2019.csv')
data_df.columns

Index(['Unnamed: 0', 'ID', 'Name', 'Age', 'Photo', 'Nationality', 'Flag',
       'Overall', 'Potential', 'Club', 'Club Logo', 'Value', 'Wage', 'Special',
       'Preferred Foot', 'International Reputation', 'Weak Foot',
       'Skill Moves', 'Work Rate', 'Body Type', 'Real Face', 'Position',
       'Jersey Number', 'Joined', 'Loaned From', 'Contract Valid Until',
       'Height', 'Weight', 'LS', 'ST', 'RS', 'LW', 'LF', 'CF', 'RF', 'RW',
       'LAM', 'CAM', 'RAM', 'LM', 'LCM', 'CM', 'RCM', 'RM', 'LWB', 'LDM',
       'CDM', 'RDM', 'RWB', 'LB', 'LCB', 'CB', 'RCB', 'RB', 'Crossing',
       'Finishing', 'HeadingAccuracy', 'ShortPassing', 'Volleys', 'Dribbling',
       'Curve', 'FKAccuracy', 'LongPassing', 'BallControl', 'Acceleration',
       'SprintSpeed', 'Agility', 'Reactions', 'Balance', 'ShotPower',
       'Jumping', 'Stamina', 'Strength', 'LongShots', 'Aggression',
       'Interceptions', 'Positioning', 'Vision', 'Penalties', 'Composure',
       'Marking', 'StandingTackle', 'SlidingTackle', 'GKDiving', 'GKHandling',
       'GKKicking', 'GKPositioning', 'GKReflexes', 'Release Clause'],
      dtype='str')

In [5]:
data_df = data_df[data_df["Position"].notnull()]
data_df.head()

,Unnamed: 0,ID,Name,Age,Photo,Nationality,Flag,Overall,Potential,Club,...,Composure,Marking,StandingTackle,SlidingTackle,GKDiving,GKHandling,GKKicking,GKPositioning,GKReflexes,Release Clause
0,0,158023,L. Messi,31,https://cdn.sofifa.org/players/4/19/158023.png,Argentina,https://cdn.sofifa.org/flags/52.png,94,94,FC Barcelona,...,96.0,33.0,28.0,26.0,6.0,11.0,15.0,14.0,8.0,€226.5M
1,1,20801,Cristiano Ronaldo,33,https://cdn.sofifa.org/players/4/19/20801.png,Portugal,https://cdn.sofifa.org/flags/38.png,94,94,Juventus,...,95.0,28.0,31.0,23.0,7.0,11.0,15.0,14.0,11.0,€127.1M
2,2,190871,Neymar Jr,26,https://cdn.sofifa.org/players/4/19/190871.png,Brazil,https://cdn.sofifa.org/flags/54.png,92,93,Paris Saint-Germain,...,94.0,27.0,24.0,33.0,9.0,9.0,15.0,15.0,11.0,€228.1M
3,3,193080,De Gea,27,https://cdn.sofifa.org/players/4/19/193080.png,Spain,https://cdn.sofifa.org/flags/45.png,91,93,Manchester United,...,68.0,15.0,21.0,13.0,90.0,85.0,87.0,88.0,94.0,€138.6M
4,4,192985,K. De Bruyne,27,https://cdn.sofifa.org/players/4/19/192985.png,Belgium,https://cdn.sofifa.org/flags/7.png,91,92,Manchester City,...,88.0,68.0,58.0,51.0,15.0,13.0,5.0,10.0,13.0,€196.4M

In [6]:
rel_cols = ["Position", 'Finishing', 'HeadingAccuracy', 'ShortPassing', 'Volleys', 'Dribbling',
            'Curve', 'FKAccuracy', 'LongPassing', 'BallControl', 'Acceleration',
            'SprintSpeed', 'Agility', 'Reactions', 'Balance', 'ShotPower',
            'Jumping', 'Stamina', 'Strength', 'LongShots', 'Aggression',
            'Interceptions', 'Positioning', 'Vision', 'Penalties', 'Composure',
            'Marking', 'StandingTackle', 'SlidingTackle', 'GKDiving', 'GKHandling',
            'GKKicking', 'GKPositioning', 'GKReflexes']

In [7]:
goalkeeper = 'GK'
forward = ['ST', 'LW', 'RW', 'LF', 'RF', 'RS','LS', 'CF']
midfielder = ['CM','RCM','LCM', 'CDM','RDM','LDM', 'CAM', 'LAM', 'RAM', 'RM', 'LM']
defender = ['CB', 'RCB', 'LCB', 'LWB', 'RWB', 'LB', 'RB']

In [8]:
data_df=data_df[rel_cols]
data_df.head()

,Position,Finishing,HeadingAccuracy,ShortPassing,Volleys,Dribbling,Curve,FKAccuracy,LongPassing,BallControl,...,Penalties,Composure,Marking,StandingTackle,SlidingTackle,GKDiving,GKHandling,GKKicking,GKPositioning,GKReflexes
0,RF,95.0,70.0,90.0,86.0,97.0,93.0,94.0,87.0,96.0,...,75.0,96.0,33.0,28.0,26.0,6.0,11.0,15.0,14.0,8.0
1,ST,94.0,89.0,81.0,87.0,88.0,81.0,76.0,77.0,94.0,...,85.0,95.0,28.0,31.0,23.0,7.0,11.0,15.0,14.0,11.0
2,LW,87.0,62.0,84.0,84.0,96.0,88.0,87.0,78.0,95.0,...,81.0,94.0,27.0,24.0,33.0,9.0,9.0,15.0,15.0,11.0
3,GK,13.0,21.0,50.0,13.0,18.0,21.0,19.0,51.0,42.0,...,40.0,68.0,15.0,21.0,13.0,90.0,85.0,87.0,88.0,94.0
4,RCM,82.0,55.0,92.0,82.0,86.0,85.0,83.0,91.0,91.0,...,79.0,88.0,68.0,58.0,51.0,15.0,13.0,5.0,10.0,13.0

In [9]:
#Assign labels to goalkeepers
data_df['Position_encoded']=0
data_df.loc[data_df["Position"] == "GK", "Position_encoded"] = 0

#Defenders
data_df.loc[data_df["Position"].isin(defender), "Position_encoded"] = 1

#Midfielders
data_df.loc[data_df["Position"].isin(midfielder), "Position_encoded"] = 2

#Forward
data_df.loc[data_df["Position"].isin(forward), "Position_encoded"] = 3

# Convert Column "Position" to numeric so that Pandas does not complain
data_df['Position_encoded'] = pd.to_numeric(data_df['Position_encoded'], downcast="integer")

In [10]:
labels=data_df['Position_encoded']
features=data_df.drop(['Position','Position_encoded'],axis=1)

In [11]:
class_names = {0: 'Goal Keeper', 1: 'Defender', 2: 'Mid-Fielder', 3: 'Forward'}

In [12]:
# splitting in train ans test datasets
X_train, X_test,y_train, y_test = train_test_split(features,labels,
                                     stratify=labels,
                                     test_size=TEST_SIZE, 
                                     random_state=RANDOM_STATE )
X_train.shape, X_test.shape,y_train.shape, y_test.shape

((14517, 33), (3630, 33), (14517,), (3630,))

In [13]:
sc=StandardScaler()
X_train=sc.fit_transform(X_train)
X_test=sc.fit_transform(X_test)

In [14]:
device=torch.device('cuda' if torch.cuda.is_available() else 'cpu')
print(f'Using device: {device}')

Using device: cpu

In [15]:
class FifaDataset(Dataset):
    def __init__(self,X,y):
        super().__init__()
        self.X=torch.tensor(X,dtype=torch.float32)
        self.y=torch.tensor(y,dtype=torch.long)

    def __len__(self):
        return len(self.X)
    def __getitem__(self,index):
        return self.X[index], self.y[index]

In [16]:
train_dataset=FifaDataset(X_train,y_train)
train_loader=DataLoader(dataset=train_dataset,batch_size=BATCH_SIZE,shuffle=True)

In [17]:
for batch_idx, (data,target) in enumerate(train_loader):
    print(f'Batch: {batch_idx +1}: ', end=' ')
    print(f'data: {data.shape}: ', end=' ')
    print(f'Target: {target.shape}: ')

Batch: 1:  data: torch.Size([32, 33]):  Target: torch.Size([32]):
Batch: 2:  data: torch.Size([32, 33]):  Target: torch.Size([32]):
Batch: 3:  data: torch.Size([32, 33]):  Target: torch.Size([32]):
Batch: 4:  data: torch.Size([32, 33]):  Target: torch.Size([32]):
Batch: 5:  data: torch.Size([32, 33]):  Target: torch.Size([32]):
Batch: 6:  data: torch.Size([32, 33]):  Target: torch.Size([32]):
Batch: 7:  data: torch.Size([32, 33]):  Target: torch.Size([32]):
Batch: 8:  data: torch.Size([32, 33]):  Target: torch.Size([32]):
Batch: 9:  data: torch.Size([32, 33]):  Target: torch.Size([32]):
Batch: 10:  data: torch.Size([32, 33]):  Target: torch.Size([32]):
Batch: 11:  data: torch.Size([32, 33]):  Target: torch.Size([32]):
Batch: 12:  data: torch.Size([32, 33]):  Target: torch.Size([32]):
Batch: 13:  data: torch.Size([32, 33]):  Target: torch.Size([32]):
Batch: 14:  data: torch.Size([32, 33]):  Target: torch.Size([32]):
Batch: 15:  data: torch.Size([32, 33]):  Target: torch.Size([32]):
Batch: 16:  data: torch.Size([32, 33]):  Target: torch.Size([32]):
Batch: 17:  data: torch.Size([32, 33]):  Target: torch.Size([32]):
Batch: 18:  data: torch.Size([32, 33]):  Target: torch.Size([32]):
Batch: 19:  data: torch.Size([32, 33]):  Target: torch.Size([32]):
Batch: 20:  data: torch.Size([32, 33]):  Target: torch.Size([32]):
Batch: 21:  data: torch.Size([32, 33]):  Target: torch.Size([32]):
Batch: 22:  data: torch.Size([32, 33]):  Target: torch.Size([32]):
Batch: 23:  data: torch.Size([32, 33]):  Target: torch.Size([32]):
Batch: 24:  data: torch.Size([32, 33]):  Target: torch.Size([32]):
Batch: 25:  data: torch.Size([32, 33]):  Target: torch.Size([32]):
Batch: 26:  data: torch.Size([32, 33]):  Target: torch.Size([32]):
Batch: 27:  data: torch.Size([32, 33]):  Target: torch.Size([32]):
Batch: 28:  data: torch.Size([32, 33]):  Target: torch.Size([32]):
Batch: 29:  data: torch.Size([32, 33]):  Target: torch.Size([32]):
Batch: 30:  data: torch.Size([32, 33]):  Target: torch.Size([32]):
Batch: 31:  data: torch.Size([32, 33]):  Target: torch.Size([32]):
Batch: 32:  data: torch.Size([32, 33]):  Target: torch.Size([32]):
Batch: 33:  data: torch.Size([32, 33]):  Target: torch.Size([32]):
Batch: 34:  data: torch.Size([32, 33]):  Target: torch.Size([32]):
Batch: 35:  data: torch.Size([32, 33]):  Target: torch.Size([32]):
Batch: 36:  data: torch.Size([32, 33]):  Target: torch.Size([32]):
Batch: 37:  data: torch.Size([32, 33]):  Target: torch.Size([32]):
Batch: 38:  data: torch.Size([32, 33]):  Target: torch.Size([32]):
Batch: 39:  data: torch.Size([32, 33]):  Target: torch.Size([32]):
Batch: 40:  data: torch.Size([32, 33]):  Target: torch.Size([32]):
Batch: 41:  data: torch.Size([32, 33]):  Target: torch.Size([32]):
Batch: 42:  data: torch.Size([32, 33]):  Target: torch.Size([32]):
Batch: 43:  data: torch.Size([32, 33]):  Target: torch.Size([32]):
Batch: 44:  data: torch.Size([32, 33]):  Target: torch.Size([32]):
Batch: 45:  data: torch.Size([32, 33]):  Target: torch.Size([32]):
Batch: 46:  data: torch.Size([32, 33]):  Target: torch.Size([32]):
Batch: 47:  data: torch.Size([32, 33]):  Target: torch.Size([32]):
Batch: 48:  data: torch.Size([32, 33]):  Target: torch.Size([32]):
Batch: 49:  data: torch.Size([32, 33]):  Target: torch.Size([32]):
Batch: 50:  data: torch.Size([32, 33]):  Target: torch.Size([32]):
Batch: 51:  data: torch.Size([32, 33]):  Target: torch.Size([32]):
Batch: 52:  data: torch.Size([32, 33]):  Target: torch.Size([32]):
Batch: 53:  data: torch.Size([32, 33]):  Target: torch.Size([32]):
Batch: 54:  data: torch.Size([32, 33]):  Target: torch.Size([32]):
Batch: 55:  data: torch.Size([32, 33]):  Target: torch.Size([32]):
Batch: 56:  data: torch.Size([32, 33]):  Target: torch.Size([32]):
Batch: 57:  data: torch.Size([32, 33]):  Target: torch.Size([32]):
Batch: 58:  data: torch.Size([32, 33]):  Target: torch.Size([32]):
Batch: 59:  data: torch.Size([32, 33]):  Target: torch.Size([32]):
Batch: 60:  data: torch.Size([32, 33]):  Target: torch.Size([32]):
Batch: 61:  data: torch.Size([32, 33]):  Target: torch.Size([32]):
Batch: 62:  data: torch.Size([32, 33]):  Target: torch.Size([32]):
Batch: 63:  data: torch.Size([32, 33]):  Target: torch.Size([32]):
Batch: 64:  data: torch.Size([32, 33]):  Target: torch.Size([32]):
Batch: 65:  data: torch.Size([32, 33]):  Target: torch.Size([32]):
Batch: 66:  data: torch.Size([32, 33]):  Target: torch.Size([32]):
Batch: 67:  data: torch.Size([32, 33]):  Target: torch.Size([32]):
Batch: 68:  data: torch.Size([32, 33]):  Target: torch.Size([32]):
Batch: 69:  data: torch.Size([32, 33]):  Target: torch.Size([32]):
Batch: 70:  data: torch.Size([32, 33]):  Target: torch.Size([32]):
Batch: 71:  data: torch.Size([32, 33]):  Target: torch.Size([32]):
Batch: 72:  data: torch.Size([32, 33]):  Target: torch.Size([32]):
Batch: 73:  data: torch.Size([32, 33]):  Target: torch.Size([32]):
Batch: 74:  data: torch.Size([32, 33]):  Target: torch.Size([32]):
Batch: 75:  data: torch.Size([32, 33]):  Target: torch.Size([32]):
Batch: 76:  data: torch.Size([32, 33]):  Target: torch.Size([32]):
Batch: 77:  data: torch.Size([32, 33]):  Target: torch.Size([32]):
Batch: 78:  data: torch.Size([32, 33]):  Target: torch.Size([32]):
Batch: 79:  data: torch.Size([32, 33]):  Target: torch.Size([32]):
Batch: 80:  data: torch.Size([32, 33]):  Target: torch.Size([32]):
Batch: 81:  data: torch.Size([32, 33]):  Target: torch.Size([32]):
Batch: 82:  data: torch.Size([32, 33]):  Target: torch.Size([32]):
Batch: 83:  data: torch.Size([32, 33]):  Target: torch.Size([32]):
Batch: 84:  data: torch.Size([32, 33]):  Target: torch.Size([32]):
Batch: 85:  data: torch.Size([32, 33]):  Target: torch.Size([32]):
Batch: 86:  data: torch.Size([32, 33]):  Target: torch.Size([32]):
Batch: 87:  data: torch.Size([32, 33]):  Target: torch.Size([32]):
Batch: 88:  data: torch.Size([32, 33]):  Target: torch.Size([32]):
Batch: 89:  data: torch.Size([32, 33]):  Target: torch.Size([32]):
Batch: 90:  data: torch.Size([32, 33]):  Target: torch.Size([32]):
Batch: 91:  data: torch.Size([32, 33]):  Target: torch.Size([32]):
Batch: 92:  data: torch.Size([32, 33]):  Target: torch.Size([32]):
Batch: 93:  data: torch.Size([32, 33]):  Target: torch.Size([32]):
Batch: 94:  data: torch.Size([32, 33]):  Target: torch.Size([32]):
Batch: 95:  data: torch.Size([32, 33]):  Target: torch.Size([32]):
Batch: 96:  data: torch.Size([32, 33]):  Target: torch.Size([32]):
Batch: 97:  data: torch.Size([32, 33]):  Target: torch.Size([32]):
Batch: 98:  data: torch.Size([32, 33]):  Target: torch.Size([32]):
Batch: 99:  data: torch.Size([32, 33]):  Target: torch.Size([32]):
Batch: 100:  data: torch.Size([32, 33]):  Target: torch.Size([32]):
Batch: 101:  data: torch.Size([32, 33]):  Target: torch.Size([32]):
Batch: 102:  data: torch.Size([32, 33]):  Target: torch.Size([32]):
Batch: 103:  data: torch.Size([32, 33]):  Target: torch.Size([32]):
Batch: 104:  data: torch.Size([32, 33]):  Target: torch.Size([32]):
Batch: 105:  data: torch.Size([32, 33]):  Target: torch.Size([32]):
Batch: 106:  data: torch.Size([32, 33]):  Target: torch.Size([32]):
Batch: 107:  data: torch.Size([32, 33]):  Target: torch.Size([32]):
Batch: 108:  data: torch.Size([32, 33]):  Target: torch.Size([32]):
Batch: 109:  data: torch.Size([32, 33]):  Target: torch.Size([32]):
Batch: 110:  data: torch.Size([32, 33]):  Target: torch.Size([32]):
Batch: 111:  data: torch.Size([32, 33]):  Target: torch.Size([32]):
Batch: 112:  data: torch.Size([32, 33]):  Target: torch.Size([32]):
Batch: 113:  data: torch.Size([32, 33]):  Target: torch.Size([32]):
Batch: 114:  data: torch.Size([32, 33]):  Target: torch.Size([32]):
Batch: 115:  data: torch.Size([32, 33]):  Target: torch.Size([32]):
Batch: 116:  data: torch.Size([32, 33]):  Target: torch.Size([32]):
Batch: 117:  data: torch.Size([32, 33]):  Target: torch.Size([32]):
Batch: 118:  data: torch.Size([32, 33]):  Target: torch.Size([32]):
Batch: 119:  data: torch.Size([32, 33]):  Target: torch.Size([32]):
Batch: 120:  data: torch.Size([32, 33]):  Target: torch.Size([32]):
Batch: 121:  data: torch.Size([32, 33]):  Target: torch.Size([32]):
Batch: 122:  data: torch.Size([32, 33]):  Target: torch.Size([32]):
Batch: 123:  data: torch.Size([32, 33]):  Target: torch.Size([32]):
Batch: 124:  data: torch.Size([32, 33]):  Target: torch.Size([32]):
Batch: 125:  data: torch.Size([32, 33]):  Target: torch.Size([32]):
Batch: 126:  data: torch.Size([32, 33]):  Target: torch.Size([32]):
Batch: 127:  data: torch.Size([32, 33]):  Target: torch.Size([32]):
Batch: 128:  data: torch.Size([32, 33]):  Target: torch.Size([32]):
Batch: 129:  data: torch.Size([32, 33]):  Target: torch.Size([32]):
Batch: 130:  data: torch.Size([32, 33]):  Target: torch.Size([32]):
Batch: 131:  data: torch.Size([32, 33]):  Target: torch.Size([32]):
Batch: 132:  data: torch.Size([32, 33]):  Target: torch.Size([32]):
Batch: 133:  data: torch.Size([32, 33]):  Target: torch.Size([32]):
Batch: 134:  data: torch.Size([32, 33]):  Target: torch.Size([32]):
Batch: 135:  data: torch.Size([32, 33]):  Target: torch.Size([32]):
Batch: 136:  data: torch.Size([32, 33]):  Target: torch.Size([32]):
Batch: 137:  data: torch.Size([32, 33]):  Target: torch.Size([32]):
Batch: 138:  data: torch.Size([32, 33]):  Target: torch.Size([32]):
Batch: 139:  data: torch.Size([32, 33]):  Target: torch.Size([32]):
Batch: 140:  data: torch.Size([32, 33]):  Target: torch.Size([32]):
Batch: 141:  data: torch.Size([32, 33]):  Target: torch.Size([32]):
Batch: 142:  data: torch.Size([32, 33]):  Target: torch.Size([32]):
Batch: 143:  data: torch.Size([32, 33]):  Target: torch.Size([32]):
Batch: 144:  data: torch.Size([32, 33]):  Target: torch.Size([32]):
Batch: 145:  data: torch.Size([32, 33]):  Target: torch.Size([32]):
Batch: 146:  data: torch.Size([32, 33]):  Target: torch.Size([32]):
Batch: 147:  data: torch.Size([32, 33]):  Target: torch.Size([32]):
Batch: 148:  data: torch.Size([32, 33]):  Target: torch.Size([32]):
Batch: 149:  data: torch.Size([32, 33]):  Target: torch.Size([32]):
Batch: 150:  data: torch.Size([32, 33]):  Target: torch.Size([32]):
Batch: 151:  data: torch.Size([32, 33]):  Target: torch.Size([32]):
Batch: 152:  data: torch.Size([32, 33]):  Target: torch.Size([32]):
Batch: 153:  data: torch.Size([32, 33]):  Target: torch.Size([32]):
Batch: 154:  data: torch.Size([32, 33]):  Target: torch.Size([32]):
Batch: 155:  data: torch.Size([32, 33]):  Target: torch.Size([32]):
Batch: 156:  data: torch.Size([32, 33]):  Target: torch.Size([32]):
Batch: 157:  data: torch.Size([32, 33]):  Target: torch.Size([32]):
Batch: 158:  data: torch.Size([32, 33]):  Target: torch.Size([32]):
Batch: 159:  data: torch.Size([32, 33]):  Target: torch.Size([32]):
Batch: 160:  data: torch.Size([32, 33]):  Target: torch.Size([32]):
Batch: 161:  data: torch.Size([32, 33]):  Target: torch.Size([32]):
Batch: 162:  data: torch.Size([32, 33]):  Target: torch.Size([32]):
Batch: 163:  data: torch.Size([32, 33]):  Target: torch.Size([32]):
Batch: 164:  data: torch.Size([32, 33]):  Target: torch.Size([32]):
Batch: 165:  data: torch.Size([32, 33]):  Target: torch.Size([32]):
Batch: 166:  data: torch.Size([32, 33]):  Target: torch.Size([32]):
Batch: 167:  data: torch.Size([32, 33]):  Target: torch.Size([32]):
Batch: 168:  data: torch.Size([32, 33]):  Target: torch.Size([32]):
Batch: 169:  data: torch.Size([32, 33]):  Target: torch.Size([32]):
Batch: 170:  data: torch.Size([32, 33]):  Target: torch.Size([32]):
Batch: 171:  data: torch.Size([32, 33]):  Target: torch.Size([32]):
Batch: 172:  data: torch.Size([32, 33]):  Target: torch.Size([32]):
Batch: 173:  data: torch.Size([32, 33]):  Target: torch.Size([32]):
Batch: 174:  data: torch.Size([32, 33]):  Target: torch.Size([32]):
Batch: 175:  data: torch.Size([32, 33]):  Target: torch.Size([32]):
Batch: 176:  data: torch.Size([32, 33]):  Target: torch.Size([32]):
Batch: 177:  data: torch.Size([32, 33]):  Target: torch.Size([32]):
Batch: 178:  data: torch.Size([32, 33]):  Target: torch.Size([32]):
Batch: 179:  data: torch.Size([32, 33]):  Target: torch.Size([32]):
Batch: 180:  data: torch.Size([32, 33]):  Target: torch.Size([32]):
Batch: 181:  data: torch.Size([32, 33]):  Target: torch.Size([32]):
Batch: 182:  data: torch.Size([32, 33]):  Target: torch.Size([32]):
Batch: 183:  data: torch.Size([32, 33]):  Target: torch.Size([32]):
Batch: 184:  data: torch.Size([32, 33]):  Target: torch.Size([32]):
Batch: 185:  data: torch.Size([32, 33]):  Target: torch.Size([32]):
Batch: 186:  data: torch.Size([32, 33]):  Target: torch.Size([32]):
Batch: 187:  data: torch.Size([32, 33]):  Target: torch.Size([32]):
Batch: 188:  data: torch.Size([32, 33]):  Target: torch.Size([32]):
Batch: 189:  data: torch.Size([32, 33]):  Target: torch.Size([32]):
Batch: 190:  data: torch.Size([32, 33]):  Target: torch.Size([32]):
Batch: 191:  data: torch.Size([32, 33]):  Target: torch.Size([32]):
Batch: 192:  data: torch.Size([32, 33]):  Target: torch.Size([32]):
Batch: 193:  data: torch.Size([32, 33]):  Target: torch.Size([32]):
Batch: 194:  data: torch.Size([32, 33]):  Target: torch.Size([32]):
Batch: 195:  data: torch.Size([32, 33]):  Target: torch.Size([32]):
Batch: 196:  data: torch.Size([32, 33]):  Target: torch.Size([32]):
Batch: 197:  data: torch.Size([32, 33]):  Target: torch.Size([32]):
Batch: 198:  data: torch.Size([32, 33]):  Target: torch.Size([32]):
Batch: 199:  data: torch.Size([32, 33]):  Target: torch.Size([32]):
Batch: 200:  data: torch.Size([32, 33]):  Target: torch.Size([32]):
Batch: 201:  data: torch.Size([32, 33]):  Target: torch.Size([32]):
Batch: 202:  data: torch.Size([32, 33]):  Target: torch.Size([32]):
Batch: 203:  data: torch.Size([32, 33]):  Target: torch.Size([32]):
Batch: 204:  data: torch.Size([32, 33]):  Target: torch.Size([32]):
Batch: 205:  data: torch.Size([32, 33]):  Target: torch.Size([32]):
Batch: 206:  data: torch.Size([32, 33]):  Target: torch.Size([32]):
Batch: 207:  data: torch.Size([32, 33]):  Target: torch.Size([32]):
Batch: 208:  data: torch.Size([32, 33]):  Target: torch.Size([32]):
Batch: 209:  data: torch.Size([32, 33]):  Target: torch.Size([32]):
Batch: 210:  data: torch.Size([32, 33]):  Target: torch.Size([32]):
Batch: 211:  data: torch.Size([32, 33]):  Target: torch.Size([32]):
Batch: 212:  data: torch.Size([32, 33]):  Target: torch.Size([32]):
Batch: 213:  data: torch.Size([32, 33]):  Target: torch.Size([32]):
Batch: 214:  data: torch.Size([32, 33]):  Target: torch.Size([32]):
Batch: 215:  data: torch.Size([32, 33]):  Target: torch.Size([32]):
Batch: 216:  data: torch.Size([32, 33]):  Target: torch.Size([32]):
Batch: 217:  data: torch.Size([32, 33]):  Target: torch.Size([32]):
Batch: 218:  data: torch.Size([32, 33]):  Target: torch.Size([32]):
Batch: 219:  data: torch.Size([32, 33]):  Target: torch.Size([32]):
Batch: 220:  data: torch.Size([32, 33]):  Target: torch.Size([32]):
Batch: 221:  data: torch.Size([32, 33]):  Target: torch.Size([32]):
Batch: 222:  data: torch.Size([32, 33]):  Target: torch.Size([32]):
Batch: 223:  data: torch.Size([32, 33]):  Target: torch.Size([32]):
Batch: 224:  data: torch.Size([32, 33]):  Target: torch.Size([32]):
Batch: 225:  data: torch.Size([32, 33]):  Target: torch.Size([32]):
Batch: 226:  data: torch.Size([32, 33]):  Target: torch.Size([32]):
Batch: 227:  data: torch.Size([32, 33]):  Target: torch.Size([32]):
Batch: 228:  data: torch.Size([32, 33]):  Target: torch.Size([32]):
Batch: 229:  data: torch.Size([32, 33]):  Target: torch.Size([32]):
Batch: 230:  data: torch.Size([32, 33]):  Target: torch.Size([32]):
Batch: 231:  data: torch.Size([32, 33]):  Target: torch.Size([32]):
Batch: 232:  data: torch.Size([32, 33]):  Target: torch.Size([32]):
Batch: 233:  data: torch.Size([32, 33]):  Target: torch.Size([32]):
Batch: 234:  data: torch.Size([32, 33]):  Target: torch.Size([32]):
Batch: 235:  data: torch.Size([32, 33]):  Target: torch.Size([32]):
Batch: 236:  data: torch.Size([32, 33]):  Target: torch.Size([32]):
Batch: 237:  data: torch.Size([32, 33]):  Target: torch.Size([32]):
Batch: 238:  data: torch.Size([32, 33]):  Target: torch.Size([32]):
Batch: 239:  data: torch.Size([32, 33]):  Target: torch.Size([32]):
Batch: 240:  data: torch.Size([32, 33]):  Target: torch.Size([32]):
Batch: 241:  data: torch.Size([32, 33]):  Target: torch.Size([32]):
Batch: 242:  data: torch.Size([32, 33]):  Target: torch.Size([32]):
Batch: 243:  data: torch.Size([32, 33]):  Target: torch.Size([32]):
Batch: 244:  data: torch.Size([32, 33]):  Target: torch.Size([32]):
Batch: 245:  data: torch.Size([32, 33]):  Target: torch.Size([32]):
Batch: 246:  data: torch.Size([32, 33]):  Target: torch.Size([32]):
Batch: 247:  data: torch.Size([32, 33]):  Target: torch.Size([32]):
Batch: 248:  data: torch.Size([32, 33]):  Target: torch.Size([32]):
Batch: 249:  data: torch.Size([32, 33]):  Target: torch.Size([32]):
Batch: 250:  data: torch.Size([32, 33]):  Target: torch.Size([32]):
Batch: 251:  data: torch.Size([32, 33]):  Target: torch.Size([32]):
Batch: 252:  data: torch.Size([32, 33]):  Target: torch.Size([32]):
Batch: 253:  data: torch.Size([32, 33]):  Target: torch.Size([32]):
Batch: 254:  data: torch.Size([32, 33]):  Target: torch.Size([32]):
Batch: 255:  data: torch.Size([32, 33]):  Target: torch.Size([32]):
Batch: 256:  data: torch.Size([32, 33]):  Target: torch.Size([32]):
Batch: 257:  data: torch.Size([32, 33]):  Target: torch.Size([32]):
Batch: 258:  data: torch.Size([32, 33]):  Target: torch.Size([32]):
Batch: 259:  data: torch.Size([32, 33]):  Target: torch.Size([32]):
Batch: 260:  data: torch.Size([32, 33]):  Target: torch.Size([32]):
Batch: 261:  data: torch.Size([32, 33]):  Target: torch.Size([32]):
Batch: 262:  data: torch.Size([32, 33]):  Target: torch.Size([32]):
Batch: 263:  data: torch.Size([32, 33]):  Target: torch.Size([32]):
Batch: 264:  data: torch.Size([32, 33]):  Target: torch.Size([32]):
Batch: 265:  data: torch.Size([32, 33]):  Target: torch.Size([32]):
Batch: 266:  data: torch.Size([32, 33]):  Target: torch.Size([32]):
Batch: 267:  data: torch.Size([32, 33]):  Target: torch.Size([32]):
Batch: 268:  data: torch.Size([32, 33]):  Target: torch.Size([32]):
Batch: 269:  data: torch.Size([32, 33]):  Target: torch.Size([32]):
Batch: 270:  data: torch.Size([32, 33]):  Target: torch.Size([32]):
Batch: 271:  data: torch.Size([32, 33]):  Target: torch.Size([32]):
Batch: 272:  data: torch.Size([32, 33]):  Target: torch.Size([32]):
Batch: 273:  data: torch.Size([32, 33]):  Target: torch.Size([32]):
Batch: 274:  data: torch.Size([32, 33]):  Target: torch.Size([32]):
Batch: 275:  data: torch.Size([32, 33]):  Target: torch.Size([32]):
Batch: 276:  data: torch.Size([32, 33]):  Target: torch.Size([32]):
Batch: 277:  data: torch.Size([32, 33]):  Target: torch.Size([32]):
Batch: 278:  data: torch.Size([32, 33]):  Target: torch.Size([32]):
Batch: 279:  data: torch.Size([32, 33]):  Target: torch.Size([32]):
Batch: 280:  data: torch.Size([32, 33]):  Target: torch.Size([32]):
Batch: 281:  data: torch.Size([32, 33]):  Target: torch.Size([32]):
Batch: 282:  data: torch.Size([32, 33]):  Target: torch.Size([32]):
Batch: 283:  data: torch.Size([32, 33]):  Target: torch.Size([32]):
Batch: 284:  data: torch.Size([32, 33]):  Target: torch.Size([32]):
Batch: 285:  data: torch.Size([32, 33]):  Target: torch.Size([32]):
Batch: 286:  data: torch.Size([32, 33]):  Target: torch.Size([32]):
Batch: 287:  data: torch.Size([32, 33]):  Target: torch.Size([32]):
Batch: 288:  data: torch.Size([32, 33]):  Target: torch.Size([32]):
Batch: 289:  data: torch.Size([32, 33]):  Target: torch.Size([32]):
Batch: 290:  data: torch.Size([32, 33]):  Target: torch.Size([32]):
Batch: 291:  data: torch.Size([32, 33]):  Target: torch.Size([32]):
Batch: 292:  data: torch.Size([32, 33]):  Target: torch.Size([32]):
Batch: 293:  data: torch.Size([32, 33]):  Target: torch.Size([32]):
Batch: 294:  data: torch.Size([32, 33]):  Target: torch.Size([32]):
Batch: 295:  data: torch.Size([32, 33]):  Target: torch.Size([32]):

In [18]:
X_train.shape, X_test.shape

((14517, 33), (3630, 33))

In [19]:
test_dataset=FifaDataset(X_test,y_test.to_numpy())
test_loader=DataLoader(dataset=train_dataset,batch_size=BATCH_SIZE, shuffle=True)

In [20]:
for batch_idx, (data,target) in enumerate(test_loader):
    print(f'Batch: {batch_idx +1}: ', end=' ')
    print(f'data: {data.shape}: ', end=' ')
    print(f'Target: {target.shape}: ')

Batch: 1:  data: torch.Size([32, 33]):  Target: torch.Size([32]):
Batch: 2:  data: torch.Size([32, 33]):  Target: torch.Size([32]):
Batch: 3:  data: torch.Size([32, 33]):  Target: torch.Size([32]):
Batch: 4:  data: torch.Size([32, 33]):  Target: torch.Size([32]):
Batch: 5:  data: torch.Size([32, 33]):  Target: torch.Size([32]):
Batch: 6:  data: torch.Size([32, 33]):  Target: torch.Size([32]):
Batch: 7:  data: torch.Size([32, 33]):  Target: torch.Size([32]):
Batch: 8:  data: torch.Size([32, 33]):  Target: torch.Size([32]):
Batch: 9:  data: torch.Size([32, 33]):  Target: torch.Size([32]):
Batch: 10:  data: torch.Size([32, 33]):  Target: torch.Size([32]):
Batch: 11:  data: torch.Size([32, 33]):  Target: torch.Size([32]):
Batch: 12:  data: torch.Size([32, 33]):  Target: torch.Size([32]):
Batch: 13:  data: torch.Size([32, 33]):  Target: torch.Size([32]):
Batch: 14:  data: torch.Size([32, 33]):  Target: torch.Size([32]):
Batch: 15:  data: torch.Size([32, 33]):  Target: torch.Size([32]):
Batch: 16:  data: torch.Size([32, 33]):  Target: torch.Size([32]):
Batch: 17:  data: torch.Size([32, 33]):  Target: torch.Size([32]):
Batch: 18:  data: torch.Size([32, 33]):  Target: torch.Size([32]):
Batch: 19:  data: torch.Size([32, 33]):  Target: torch.Size([32]):
Batch: 20:  data: torch.Size([32, 33]):  Target: torch.Size([32]):
Batch: 21:  data: torch.Size([32, 33]):  Target: torch.Size([32]):
Batch: 22:  data: torch.Size([32, 33]):  Target: torch.Size([32]):
Batch: 23:  data: torch.Size([32, 33]):  Target: torch.Size([32]):
Batch: 24:  data: torch.Size([32, 33]):  Target: torch.Size([32]):
Batch: 25:  data: torch.Size([32, 33]):  Target: torch.Size([32]):
Batch: 26:  data: torch.Size([32, 33]):  Target: torch.Size([32]):
Batch: 27:  data: torch.Size([32, 33]):  Target: torch.Size([32]):
Batch: 28:  data: torch.Size([32, 33]):  Target: torch.Size([32]):
Batch: 29:  data: torch.Size([32, 33]):  Target: torch.Size([32]):
Batch: 30:  data: torch.Size([32, 33]):  Target: torch.Size([32]):
Batch: 31:  data: torch.Size([32, 33]):  Target: torch.Size([32]):
Batch: 32:  data: torch.Size([32, 33]):  Target: torch.Size([32]):
Batch: 33:  data: torch.Size([32, 33]):  Target: torch.Size([32]):
Batch: 34:  data: torch.Size([32, 33]):  Target: torch.Size([32]):
Batch: 35:  data: torch.Size([32, 33]):  Target: torch.Size([32]):
Batch: 36:  data: torch.Size([32, 33]):  Target: torch.Size([32]):
Batch: 37:  data: torch.Size([32, 33]):  Target: torch.Size([32]):
Batch: 38:  data: torch.Size([32, 33]):  Target: torch.Size([32]):
Batch: 39:  data: torch.Size([32, 33]):  Target: torch.Size([32]):
Batch: 40:  data: torch.Size([32, 33]):  Target: torch.Size([32]):
Batch: 41:  data: torch.Size([32, 33]):  Target: torch.Size([32]):
Batch: 42:  data: torch.Size([32, 33]):  Target: torch.Size([32]):
Batch: 43:  data: torch.Size([32, 33]):  Target: torch.Size([32]):
Batch: 44:  data: torch.Size([32, 33]):  Target: torch.Size([32]):
Batch: 45:  data: torch.Size([32, 33]):  Target: torch.Size([32]):
Batch: 46:  data: torch.Size([32, 33]):  Target: torch.Size([32]):
Batch: 47:  data: torch.Size([32, 33]):  Target: torch.Size([32]):
Batch: 48:  data: torch.Size([32, 33]):  Target: torch.Size([32]):
Batch: 49:  data: torch.Size([32, 33]):  Target: torch.Size([32]):
Batch: 50:  data: torch.Size([32, 33]):  Target: torch.Size([32]):
Batch: 51:  data: torch.Size([32, 33]):  Target: torch.Size([32]):
Batch: 52:  data: torch.Size([32, 33]):  Target: torch.Size([32]):
Batch: 53:  data: torch.Size([32, 33]):  Target: torch.Size([32]):
Batch: 54:  data: torch.Size([32, 33]):  Target: torch.Size([32]):
Batch: 55:  data: torch.Size([32, 33]):  Target: torch.Size([32]):
Batch: 56:  data: torch.Size([32, 33]):  Target: torch.Size([32]):
Batch: 57:  data: torch.Size([32, 33]):  Target: torch.Size([32]):
Batch: 58:  data: torch.Size([32, 33]):  Target: torch.Size([32]):
Batch: 59:  data: torch.Size([32, 33]):  Target: torch.Size([32]):
Batch: 60:  data: torch.Size([32, 33]):  Target: torch.Size([32]):
Batch: 61:  data: torch.Size([32, 33]):  Target: torch.Size([32]):
Batch: 62:  data: torch.Size([32, 33]):  Target: torch.Size([32]):
Batch: 63:  data: torch.Size([32, 33]):  Target: torch.Size([32]):
Batch: 64:  data: torch.Size([32, 33]):  Target: torch.Size([32]):
Batch: 65:  data: torch.Size([32, 33]):  Target: torch.Size([32]):
Batch: 66:  data: torch.Size([32, 33]):  Target: torch.Size([32]):
Batch: 67:  data: torch.Size([32, 33]):  Target: torch.Size([32]):
Batch: 68:  data: torch.Size([32, 33]):  Target: torch.Size([32]):
Batch: 69:  data: torch.Size([32, 33]):  Target: torch.Size([32]):
Batch: 70:  data: torch.Size([32, 33]):  Target: torch.Size([32]):
Batch: 71:  data: torch.Size([32, 33]):  Target: torch.Size([32]):
Batch: 72:  data: torch.Size([32, 33]):  Target: torch.Size([32]):
Batch: 73:  data: torch.Size([32, 33]):  Target: torch.Size([32]):
Batch: 74:  data: torch.Size([32, 33]):  Target: torch.Size([32]):
Batch: 75:  data: torch.Size([32, 33]):  Target: torch.Size([32]):
Batch: 76:  data: torch.Size([32, 33]):  Target: torch.Size([32]):
Batch: 77:  data: torch.Size([32, 33]):  Target: torch.Size([32]):
Batch: 78:  data: torch.Size([32, 33]):  Target: torch.Size([32]):
Batch: 79:  data: torch.Size([32, 33]):  Target: torch.Size([32]):
Batch: 80:  data: torch.Size([32, 33]):  Target: torch.Size([32]):
Batch: 81:  data: torch.Size([32, 33]):  Target: torch.Size([32]):
Batch: 82:  data: torch.Size([32, 33]):  Target: torch.Size([32]):
Batch: 83:  data: torch.Size([32, 33]):  Target: torch.Size([32]):
Batch: 84:  data: torch.Size([32, 33]):  Target: torch.Size([32]):
Batch: 85:  data: torch.Size([32, 33]):  Target: torch.Size([32]):
Batch: 86:  data: torch.Size([32, 33]):  Target: torch.Size([32]):
Batch: 87:  data: torch.Size([32, 33]):  Target: torch.Size([32]):
Batch: 88:  data: torch.Size([32, 33]):  Target: torch.Size([32]):
Batch: 89:  data: torch.Size([32, 33]):  Target: torch.Size([32]):
Batch: 90:  data: torch.Size([32, 33]):  Target: torch.Size([32]):
Batch: 91:  data: torch.Size([32, 33]):  Target: torch.Size([32]):
Batch: 92:  data: torch.Size([32, 33]):  Target: torch.Size([32]):
Batch: 93:  data: torch.Size([32, 33]):  Target: torch.Size([32]):
Batch: 94:  data: torch.Size([32, 33]):  Target: torch.Size([32]):
Batch: 95:  data: torch.Size([32, 33]):  Target: torch.Size([32]):
Batch: 96:  data: torch.Size([32, 33]):  Target: torch.Size([32]):
Batch: 97:  data: torch.Size([32, 33]):  Target: torch.Size([32]):
Batch: 98:  data: torch.Size([32, 33]):  Target: torch.Size([32]):
Batch: 99:  data: torch.Size([32, 33]):  Target: torch.Size([32]):
Batch: 100:  data: torch.Size([32, 33]):  Target: torch.Size([32]):
Batch: 101:  data: torch.Size([32, 33]):  Target: torch.Size([32]):
Batch: 102:  data: torch.Size([32, 33]):  Target: torch.Size([32]):
Batch: 103:  data: torch.Size([32, 33]):  Target: torch.Size([32]):
Batch: 104:  data: torch.Size([32, 33]):  Target: torch.Size([32]):
Batch: 105:  data: torch.Size([32, 33]):  Target: torch.Size([32]):
Batch: 106:  data: torch.Size([32, 33]):  Target: torch.Size([32]):
Batch: 107:  data: torch.Size([32, 33]):  Target: torch.Size([32]):
Batch: 108:  data: torch.Size([32, 33]):  Target: torch.Size([32]):
Batch: 109:  data: torch.Size([32, 33]):  Target: torch.Size([32]):
Batch: 110:  data: torch.Size([32, 33]):  Target: torch.Size([32]):
Batch: 111:  data: torch.Size([32, 33]):  Target: torch.Size([32]):
Batch: 112:  data: torch.Size([32, 33]):  Target: torch.Size([32]):
Batch: 113:  data: torch.Size([32, 33]):  Target: torch.Size([32]):
Batch: 114:  data: torch.Size([32, 33]):  Target: torch.Size([32]):
Batch: 115:  data: torch.Size([32, 33]):  Target: torch.Size([32]):
Batch: 116:  data: torch.Size([32, 33]):  Target: torch.Size([32]):
Batch: 117:  data: torch.Size([32, 33]):  Target: torch.Size([32]):
Batch: 118:  data: torch.Size([32, 33]):  Target: torch.Size([32]):
Batch: 119:  data: torch.Size([32, 33]):  Target: torch.Size([32]):
Batch: 120:  data: torch.Size([32, 33]):  Target: torch.Size([32]):
Batch: 121:  data: torch.Size([32, 33]):  Target: torch.Size([32]):
Batch: 122:  data: torch.Size([32, 33]):  Target: torch.Size([32]):
Batch: 123:  data: torch.Size([32, 33]):  Target: torch.Size([32]):
Batch: 124:  data: torch.Size([32, 33]):  Target: torch.Size([32]):
Batch: 125:  data: torch.Size([32, 33]):  Target: torch.Size([32]):
Batch: 126:  data: torch.Size([32, 33]):  Target: torch.Size([32]):
Batch: 127:  data: torch.Size([32, 33]):  Target: torch.Size([32]):
Batch: 128:  data: torch.Size([32, 33]):  Target: torch.Size([32]):
Batch: 129:  data: torch.Size([32, 33]):  Target: torch.Size([32]):
Batch: 130:  data: torch.Size([32, 33]):  Target: torch.Size([32]):
Batch: 131:  data: torch.Size([32, 33]):  Target: torch.Size([32]):
Batch: 132:  data: torch.Size([32, 33]):  Target: torch.Size([32]):
Batch: 133:  data: torch.Size([32, 33]):  Target: torch.Size([32]):
Batch: 134:  data: torch.Size([32, 33]):  Target: torch.Size([32]):
Batch: 135:  data: torch.Size([32, 33]):  Target: torch.Size([32]):
Batch: 136:  data: torch.Size([32, 33]):  Target: torch.Size([32]):
Batch: 137:  data: torch.Size([32, 33]):  Target: torch.Size([32]):
Batch: 138:  data: torch.Size([32, 33]):  Target: torch.Size([32]):
Batch: 139:  data: torch.Size([32, 33]):  Target: torch.Size([32]):
Batch: 140:  data: torch.Size([32, 33]):  Target: torch.Size([32]):
Batch: 141:  data: torch.Size([32, 33]):  Target: torch.Size([32]):
Batch: 142:  data: torch.Size([32, 33]):  Target: torch.Size([32]):
Batch: 143:  data: torch.Size([32, 33]):  Target: torch.Size([32]):
Batch: 144:  data: torch.Size([32, 33]):  Target: torch.Size([32]):
Batch: 145:  data: torch.Size([32, 33]):  Target: torch.Size([32]):
Batch: 146:  data: torch.Size([32, 33]):  Target: torch.Size([32]):
Batch: 147:  data: torch.Size([32, 33]):  Target: torch.Size([32]):
Batch: 148:  data: torch.Size([32, 33]):  Target: torch.Size([32]):
Batch: 149:  data: torch.Size([32, 33]):  Target: torch.Size([32]):
Batch: 150:  data: torch.Size([32, 33]):  Target: torch.Size([32]):
Batch: 151:  data: torch.Size([32, 33]):  Target: torch.Size([32]):
Batch: 152:  data: torch.Size([32, 33]):  Target: torch.Size([32]):
Batch: 153:  data: torch.Size([32, 33]):  Target: torch.Size([32]):
Batch: 154:  data: torch.Size([32, 33]):  Target: torch.Size([32]):
Batch: 155:  data: torch.Size([32, 33]):  Target: torch.Size([32]):
Batch: 156:  data: torch.Size([32, 33]):  Target: torch.Size([32]):
Batch: 157:  data: torch.Size([32, 33]):  Target: torch.Size([32]):
Batch: 158:  data: torch.Size([32, 33]):  Target: torch.Size([32]):
Batch: 159:  data: torch.Size([32, 33]):  Target: torch.Size([32]):
Batch: 160:  data: torch.Size([32, 33]):  Target: torch.Size([32]):
Batch: 161:  data: torch.Size([32, 33]):  Target: torch.Size([32]):
Batch: 162:  data: torch.Size([32, 33]):  Target: torch.Size([32]):
Batch: 163:  data: torch.Size([32, 33]):  Target: torch.Size([32]):
Batch: 164:  data: torch.Size([32, 33]):  Target: torch.Size([32]):
Batch: 165:  data: torch.Size([32, 33]):  Target: torch.Size([32]):
Batch: 166:  data: torch.Size([32, 33]):  Target: torch.Size([32]):
Batch: 167:  data: torch.Size([32, 33]):  Target: torch.Size([32]):
Batch: 168:  data: torch.Size([32, 33]):  Target: torch.Size([32]):
Batch: 169:  data: torch.Size([32, 33]):  Target: torch.Size([32]):
Batch: 170:  data: torch.Size([32, 33]):  Target: torch.Size([32]):
Batch: 171:  data: torch.Size([32, 33]):  Target: torch.Size([32]):
Batch: 172:  data: torch.Size([32, 33]):  Target: torch.Size([32]):
Batch: 173:  data: torch.Size([32, 33]):  Target: torch.Size([32]):
Batch: 174:  data: torch.Size([32, 33]):  Target: torch.Size([32]):
Batch: 175:  data: torch.Size([32, 33]):  Target: torch.Size([32]):
Batch: 176:  data: torch.Size([32, 33]):  Target: torch.Size([32]):
Batch: 177:  data: torch.Size([32, 33]):  Target: torch.Size([32]):
Batch: 178:  data: torch.Size([32, 33]):  Target: torch.Size([32]):
Batch: 179:  data: torch.Size([32, 33]):  Target: torch.Size([32]):
Batch: 180:  data: torch.Size([32, 33]):  Target: torch.Size([32]):
Batch: 181:  data: torch.Size([32, 33]):  Target: torch.Size([32]):
Batch: 182:  data: torch.Size([32, 33]):  Target: torch.Size([32]):
Batch: 183:  data: torch.Size([32, 33]):  Target: torch.Size([32]):
Batch: 184:  data: torch.Size([32, 33]):  Target: torch.Size([32]):
Batch: 185:  data: torch.Size([32, 33]):  Target: torch.Size([32]):
Batch: 186:  data: torch.Size([32, 33]):  Target: torch.Size([32]):
Batch: 187:  data: torch.Size([32, 33]):  Target: torch.Size([32]):
Batch: 188:  data: torch.Size([32, 33]):  Target: torch.Size([32]):
Batch: 189:  data: torch.Size([32, 33]):  Target: torch.Size([32]):
Batch: 190:  data: torch.Size([32, 33]):  Target: torch.Size([32]):
Batch: 191:  data: torch.Size([32, 33]):  Target: torch.Size([32]):
Batch: 192:  data: torch.Size([32, 33]):  Target: torch.Size([32]):
Batch: 193:  data: torch.Size([32, 33]):  Target: torch.Size([32]):
Batch: 194:  data: torch.Size([32, 33]):  Target: torch.Size([32]):
Batch: 195:  data: torch.Size([32, 33]):  Target: torch.Size([32]):
Batch: 196:  data: torch.Size([32, 33]):  Target: torch.Size([32]):
Batch: 197:  data: torch.Size([32, 33]):  Target: torch.Size([32]):
Batch: 198:  data: torch.Size([32, 33]):  Target: torch.Size([32]):
Batch: 199:  data: torch.Size([32, 33]):  Target: torch.Size([32]):
Batch: 200:  data: torch.Size([32, 33]):  Target: torch.Size([32]):
Batch: 201:  data: torch.Size([32, 33]):  Target: torch.Size([32]):
Batch: 202:  data: torch.Size([32, 33]):  Target: torch.Size([32]):
Batch: 203:  data: torch.Size([32, 33]):  Target: torch.Size([32]):
Batch: 204:  data: torch.Size([32, 33]):  Target: torch.Size([32]):
Batch: 205:  data: torch.Size([32, 33]):  Target: torch.Size([32]):
Batch: 206:  data: torch.Size([32, 33]):  Target: torch.Size([32]):
Batch: 207:  data: torch.Size([32, 33]):  Target: torch.Size([32]):
Batch: 208:  data: torch.Size([32, 33]):  Target: torch.Size([32]):
Batch: 209:  data: torch.Size([32, 33]):  Target: torch.Size([32]):
Batch: 210:  data: torch.Size([32, 33]):  Target: torch.Size([32]):
Batch: 211:  data: torch.Size([32, 33]):  Target: torch.Size([32]):
Batch: 212:  data: torch.Size([32, 33]):  Target: torch.Size([32]):
Batch: 213:  data: torch.Size([32, 33]):  Target: torch.Size([32]):
Batch: 214:  data: torch.Size([32, 33]):  Target: torch.Size([32]):
Batch: 215:  data: torch.Size([32, 33]):  Target: torch.Size([32]):
Batch: 216:  data: torch.Size([32, 33]):  Target: torch.Size([32]):
Batch: 217:  data: torch.Size([32, 33]):  Target: torch.Size([32]):
Batch: 218:  data: torch.Size([32, 33]):  Target: torch.Size([32]):
Batch: 219:  data: torch.Size([32, 33]):  Target: torch.Size([32]):
Batch: 220:  data: torch.Size([32, 33]):  Target: torch.Size([32]):
Batch: 221:  data: torch.Size([32, 33]):  Target: torch.Size([32]):
Batch: 222:  data: torch.Size([32, 33]):  Target: torch.Size([32]):
Batch: 223:  data: torch.Size([32, 33]):  Target: torch.Size([32]):
Batch: 224:  data: torch.Size([32, 33]):  Target: torch.Size([32]):
Batch: 225:  data: torch.Size([32, 33]):  Target: torch.Size([32]):
Batch: 226:  data: torch.Size([32, 33]):  Target: torch.Size([32]):
Batch: 227:  data: torch.Size([32, 33]):  Target: torch.Size([32]):
Batch: 228:  data: torch.Size([32, 33]):  Target: torch.Size([32]):
Batch: 229:  data: torch.Size([32, 33]):  Target: torch.Size([32]):
Batch: 230:  data: torch.Size([32, 33]):  Target: torch.Size([32]):
Batch: 231:  data: torch.Size([32, 33]):  Target: torch.Size([32]):
Batch: 232:  data: torch.Size([32, 33]):  Target: torch.Size([32]):
Batch: 233:  data: torch.Size([32, 33]):  Target: torch.Size([32]):
Batch: 234:  data: torch.Size([32, 33]):  Target: torch.Size([32]):
Batch: 235:  data: torch.Size([32, 33]):  Target: torch.Size([32]):
Batch: 236:  data: torch.Size([32, 33]):  Target: torch.Size([32]):
Batch: 237:  data: torch.Size([32, 33]):  Target: torch.Size([32]):
Batch: 238:  data: torch.Size([32, 33]):  Target: torch.Size([32]):
Batch: 239:  data: torch.Size([32, 33]):  Target: torch.Size([32]):
Batch: 240:  data: torch.Size([32, 33]):  Target: torch.Size([32]):
Batch: 241:  data: torch.Size([32, 33]):  Target: torch.Size([32]):
Batch: 242:  data: torch.Size([32, 33]):  Target: torch.Size([32]):
Batch: 243:  data: torch.Size([32, 33]):  Target: torch.Size([32]):
Batch: 244:  data: torch.Size([32, 33]):  Target: torch.Size([32]):
Batch: 245:  data: torch.Size([32, 33]):  Target: torch.Size([32]):
Batch: 246:  data: torch.Size([32, 33]):  Target: torch.Size([32]):
Batch: 247:  data: torch.Size([32, 33]):  Target: torch.Size([32]):
Batch: 248:  data: torch.Size([32, 33]):  Target: torch.Size([32]):
Batch: 249:  data: torch.Size([32, 33]):  Target: torch.Size([32]):
Batch: 250:  data: torch.Size([32, 33]):  Target: torch.Size([32]):
Batch: 251:  data: torch.Size([32, 33]):  Target: torch.Size([32]):
Batch: 252:  data: torch.Size([32, 33]):  Target: torch.Size([32]):
Batch: 253:  data: torch.Size([32, 33]):  Target: torch.Size([32]):
Batch: 254:  data: torch.Size([32, 33]):  Target: torch.Size([32]):
Batch: 255:  data: torch.Size([32, 33]):  Target: torch.Size([32]):
Batch: 256:  data: torch.Size([32, 33]):  Target: torch.Size([32]):
Batch: 257:  data: torch.Size([32, 33]):  Target: torch.Size([32]):
Batch: 258:  data: torch.Size([32, 33]):  Target: torch.Size([32]):
Batch: 259:  data: torch.Size([32, 33]):  Target: torch.Size([32]):
Batch: 260:  data: torch.Size([32, 33]):  Target: torch.Size([32]):
Batch: 261:  data: torch.Size([32, 33]):  Target: torch.Size([32]):
Batch: 262:  data: torch.Size([32, 33]):  Target: torch.Size([32]):
Batch: 263:  data: torch.Size([32, 33]):  Target: torch.Size([32]):
Batch: 264:  data: torch.Size([32, 33]):  Target: torch.Size([32]):
Batch: 265:  data: torch.Size([32, 33]):  Target: torch.Size([32]):
Batch: 266:  data: torch.Size([32, 33]):  Target: torch.Size([32]):
Batch: 267:  data: torch.Size([32, 33]):  Target: torch.Size([32]):
Batch: 268:  data: torch.Size([32, 33]):  Target: torch.Size([32]):
Batch: 269:  data: torch.Size([32, 33]):  Target: torch.Size([32]):
Batch: 270:  data: torch.Size([32, 33]):  Target: torch.Size([32]):
Batch: 271:  data: torch.Size([32, 33]):  Target: torch.Size([32]):
Batch: 272:  data: torch.Size([32, 33]):  Target: torch.Size([32]):
Batch: 273:  data: torch.Size([32, 33]):  Target: torch.Size([32]):
Batch: 274:  data: torch.Size([32, 33]):  Target: torch.Size([32]):
Batch: 275:  data: torch.Size([32, 33]):  Target: torch.Size([32]):
Batch: 276:  data: torch.Size([32, 33]):  Target: torch.Size([32]):
Batch: 277:  data: torch.Size([32, 33]):  Target: torch.Size([32]):
Batch: 278:  data: torch.Size([32, 33]):  Target: torch.Size([32]):
Batch: 279:  data: torch.Size([32, 33]):  Target: torch.Size([32]):
Batch: 280:  data: torch.Size([32, 33]):  Target: torch.Size([32]):
Batch: 281:  data: torch.Size([32, 33]):  Target: torch.Size([32]):
Batch: 282:  data: torch.Size([32, 33]):  Target: torch.Size([32]):
Batch: 283:  data: torch.Size([32, 33]):  Target: torch.Size([32]):
Batch: 284:  data: torch.Size([32, 33]):  Target: torch.Size([32]):
Batch: 285:  data: torch.Size([32, 33]):  Target: torch.Size([32]):
Batch: 286:  data: torch.Size([32, 33]):  Target: torch.Size([32]):
Batch: 287:  data: torch.Size([32, 33]):  Target: torch.Size([32]):
Batch: 288:  data: torch.Size([32, 33]):  Target: torch.Size([32]):
Batch: 289:  data: torch.Size([32, 33]):  Target: torch.Size([32]):
Batch: 290:  data: torch.Size([32, 33]):  Target: torch.Size([32]):
Batch: 291:  data: torch.Size([32, 33]):  Target: torch.Size([32]):
Batch: 292:  data: torch.Size([32, 33]):  Target: torch.Size([32]):
Batch: 293:  data: torch.Size([32, 33]):  Target: torch.Size([32]):
Batch: 294:  data: torch.Size([32, 33]):  Target: torch.Size([32]):
Batch: 295:  data: torch.Size([32, 33]):  Target: torch.Size([32]):

In [22]:
class FifaModel(nn.Module):

    '''Layers:
    33  -> 16 -> 8-> 4
    
    '''
    def __init__(self,input_dim):
        super(FifaModel,self).__init__()
        self.layer1=nn.Linear(input_dim,16)
        self.active1=nn.ReLU()
        
        self.layer2=nn.Linear(16,8)
        self.active2=nn.ReLU()

        self.layer3=nn.Linear(8,4)
    
    def forward(self,x):
        x=self.layer1(x)
        x=self.active1(x)
        x=self.layer2(x)
        x=self.active2(x)
        x=self.layer3(x)
        return x

model=FifaModel(input_dim=X_train.shape[1]).to(device=device)

In [ ]:
# for features, labels

In [23]:
loss_fn=nn.CrossEntropyLoss()
optimizer=torch.optim.Adam(model.parameters(),lr=ALPHA)

loss,tloss,n_epoch,acc,tacc=[],[],[],[],[]
for epoch in range(EPOCHS):
    model.train()
    epoch_loss=0
    epoch_acc=0
    tepoch_loss=0
    tepoch_acc=0

    for batch_idx,(train_X,train_y) in enumerate(train_loader):
        train_X,train_y=train_X.to(device),train_y.to(device)
        predict_prob=model(train_X)
        batch_loss=loss_fn(predict_prob,train_y)
        epoch_loss+=(batch_loss-epoch_loss)/(batch_idx+1)

        optimizer.zero_grad()
        batch_loss.backward()
        optimizer.step()

        _, y_pred=torch.max(predict_prob,1)
        batch_acc=accuracy_score(train_y.cpu().numpy(),
                                y_pred.data.cpu())