In [9]:
import numpy as np
import pandas as pd
from sklearn.tree import DecisionTreeClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.naive_bayes import GaussianNB
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder, OneHotEncoder
from sklearn.metrics import accuracy_score,log_loss,r2_score
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import BaggingClassifier
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis

In [10]:
kyph=pd.read_csv("D:\\AshleshaRuchika\\PGCP-AI\\Machine Learning\\Kyphosis\\Kyphosis.csv")
kyph

   Kyphosis  Age  Number  Start
0    absent   71       3      5
1    absent  158       3     14
2   present  128       4      5
3    absent    2       5      1
4    absent    1       4     15
..      ...  ...     ...    ...
76  present  157       3     13
77   absent   26       7     13
78   absent  120       2     13
79  present   42       7      6
80   absent   36       4     13

[81 rows x 4 columns]

In [11]:
X,y=kyph.drop("Kyphosis",axis=1),kyph["Kyphosis"]
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.3,random_state=26,stratify=y)

In [17]:
knn=KNeighborsClassifier(n_neighbors=3)
bagg=BaggingClassifier(random_state=26,estimator=knn,n_estimators=15)
bagg.fit(X_train,y_train)
y_pred=bagg.predict(X_test)
accuracy_score(y_test,y_pred)

0.8

In [27]:
Ks=[1,2,3,4,5,6,7,8,9,10]
scores=[]
for k in Ks:
    knn=KNeighborsClassifier(n_neighbors=k)
    bagg=BaggingClassifier(random_state=26,estimator=knn,n_estimators=15)
    bagg.fit(X_train,y_train)
    y_pred_prob=bagg.predict_proba(X_test)
    scores.append([k,log_loss(y_test,y_pred_prob)])
df_scores=pd.DataFrame(scores,columns=["K","scores"])
df_scores.sort_values("scores",ascending=True)

    K    scores
9  10  0.624843
8   9  0.651750
7   8  1.910555
6   7  1.934501
5   6  1.977256
4   5  2.021348
3   4  4.604602
2   3  4.608046
1   2  4.668663
0   1  5.994604

In [31]:
C=[1,2,3,4,5,6,7,8,9,10]
Cs=np.linspace(0.001,5,10)
scores=[]
for c in C:
    lr=LogisticRegression(C=c)
    bagg=BaggingClassifier(random_state=26,estimator=lr,n_estimators=15)
    bagg.fit(X_train,y_train)
    y_pred_prob=bagg.predict_proba(X_test)
    scores.append([k,log_loss(y_test,y_pred_prob)])
df_scores=pd.DataFrame(scores,columns=["C","score"])
df_scores.sort_values("score",ascending=True)

    C     score
0  10  0.360632
1  10  0.362476
2  10  0.363139
3  10  0.363492
4  10  0.363731
5  10  0.363925
6  10  0.364099
7  10  0.364263
8  10  0.364423
9  10  0.364574

In [48]:
lr=LogisticRegression()
knn=KNeighborsClassifier()
dtc=DecisionTreeClassifier(random_state=26)
lda=LinearDiscriminantAnalysis()
nb=GaussianNB()
scores=[]
estmes=[lr,knn,lda,nb]
for e in estmes:
    for n in [10,15,50,100]:
        bagg=BaggingClassifier(random_state=26,estimator=e,n_estimators=n)
        bagg.fit(X_train,y_train)
        y_pred_prob=bagg.predict_proba(X_test)
        scores.append([e,n,log_loss(y_test,y_pred_prob)])
df_scores=pd.DataFrame(scores,columns=["Model","n_est","score"])
df_scores.sort_values("score",ascending=True)

                           Model  n_est     score
2           LogisticRegression()     50  0.351872
10  LinearDiscriminantAnalysis()     50  0.354924
3           LogisticRegression()    100  0.355435
1           LogisticRegression()     15  0.360632
11  LinearDiscriminantAnalysis()    100  0.360662
9   LinearDiscriminantAnalysis()     15  0.363842
0           LogisticRegression()     10  0.363875
8   LinearDiscriminantAnalysis()     10  0.369988
14                  GaussianNB()     50  0.411576
15                  GaussianNB()    100  0.420313
13                  GaussianNB()     15  0.431895
12                  GaussianNB()     10  0.446283
4         KNeighborsClassifier()     10  2.008465
6         KNeighborsClassifier()     50  2.012137
7         KNeighborsClassifier()    100  2.018874
5         KNeighborsClassifier()     15  2.021348

In [ ]:
X,y=hr.drop("left",axis=1),hr["left"]
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.3,random_state=26,stratify=y)