In [19]:
import numpy as np
import os
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression, ElasticNet
from sklearn.metrics import mean_absolute_error, root_mean_squared_error, r2_score
os.chdir("D:\\AshleshaRuchika\\PGCP-AI\\Machine Learning\\Concrete_Strength")

In [27]:
concretedata=pd.read_csv("Concrete_Data.csv")
concretedata

,Cement,Blast,Fly,Water,Superplasticizer,Coarse,Fine,Age,Strength
0,540.0,0.0,0.0,162.0,2.5,1040.0,676.0,28,79.99
1,540.0,0.0,0.0,162.0,2.5,1055.0,676.0,28,61.89
2,332.5,142.5,0.0,228.0,0.0,932.0,594.0,270,40.27
3,332.5,142.5,0.0,228.0,0.0,932.0,594.0,365,41.05
4,198.6,132.4,0.0,192.0,0.0,978.4,825.5,360,44.30
...,...,...,...,...,...,...,...,...,...
1025,276.4,116.0,90.3,179.6,8.9,870.1,768.3,28,44.28
1026,322.2,0.0,115.6,196.0,10.4,817.9,813.4,28,31.18
1027,148.5,139.4,108.6,192.7,6.1,892.4,780.0,28,23.70
1028,159.1,186.7,0.0,175.6,11.3,989.6,788.9,28,32.77
1029,260.9,100.5,78.3,200.6,8.6,864.5,761.5,28,32.40

In [30]:
#infercing
# 1. fit the best model on the whole data
X=concretedata.drop("Strength",axis=1)
y=concretedata["Strength"]
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.3,random_state=26)
lr=LinearRegression()
lr.fit(X_train,y_train)
y_pred=lr.predict(X_test)
print("MAE=",mean_absolute_error(y_test,y_pred))
print("MSE=",root_mean_squared_error(y_test,y_pred))
print("R2=",r2_score(y_test,y_pred))

MAE= 8.917193654346542
MSE= 10.960745667460321
R2= 0.6181464728464399

In [31]:
bm=ElasticNet(alpha=5,l1_ratio=0.26158)
bm.fit(X,y)

ElasticNet(alpha=5, l1_ratio=0.26158)

In [34]:
tst=pd.read_csv("testConcrete.csv")
tst

    Cement  Blast  Fly  Water  Superplasticizer  Coarse  Fine  Age
0      495    120    0    155                 5     866   884   75
1      262    129    0    271                 2     808   787  174
2      201     48    1    215                 5     807   839  113
3      329    141    0    286                 1     881   823  229
4      354     14    0    129                 2     839   847  210
5      150     23   23    114                 4     883   638   36
6      480     64    0    292                 3     896   776  180
7      393     49   82    132                 1     887   830  271
8      284     63    1    138                 1     804   725   44
9      206     38    0    103                 2     818   719  191
10     247     64   26    175                 2     822   898  183
11     223    102    0    110                 2     808   854  270
12     457     89    0    289                 3     829   865  190
13     125     93    0    200                 5     893   671  113

In [35]:
tst['predicted']=bm.predict(tst)
tst

    Cement  Blast  Fly  Water  Superplasticizer  Coarse  Fine  Age  predicted
0      495    120    0    155                 5     866   884   75  69.421469
1      262    129    0    271                 2     808   787  174  30.545684
2      201     48    1    215                 5     807   839  113  19.541163
3      329    141    0    286                 1     881   823  229  44.611985
4      354     14    0    129                 2     839   847  210  60.418802
5      150     23   23    114                 4     883   638   36  19.534908
6      480     64    0    292                 3     896   776  180  47.752411
7      393     49   82    132                 1     887   830  271  82.349092
8      284     63    1    138                 1     804   725   44  34.151037
9      206     38    0    103                 2     818   719  191  45.418146
10     247     64   26    175                 2     822   898  183  44.535255
11     223    102    0    110                 2     808   854  270  63.791990
12     457     89    0    289                 3     829   865  190  49.894810
13     125     93    0    200                 5     893   671  113  15.976758

FileNotFoundError: [Errno 2] No such file or directory: 'Housing.csv'