In [1]:
sent1='It was a beautiful rainy day that made mu day awesome.'
sent2='We made it awesome by adding more flavors in it'

In [2]:
from sklearn.feature_extraction.text import TfidfVectorizer

In [4]:
tfidf=TfidfVectorizer()

In [5]:
new=tfidf.fit_transform([sent1,sent2])

In [6]:
import pandas as pd

In [7]:
df=pd.DataFrame(new.toarray(), columns=tfidf.get_feature_names_out())

In [8]:
df

     adding   awesome  beautiful        by       day  ...        mu     rainy      that       was        we
0  0.000000  0.219381   0.308332  0.000000  0.616664  ...  0.308332  0.308332  0.308332  0.308332  0.000000
1  0.332642  0.236677   0.000000  0.332642  0.000000  ...  0.000000  0.000000  0.000000  0.000000  0.332642

[2 rows x 15 columns]

In [ ]:
#File-mreviews.txt

In [9]:
f=open('mreviews.txt')
lines=f.readlines()

In [10]:
tfidf=TfidfVectorizer(stop_words='english')
new=tfidf.fit_transform(lines)
df=pd.DataFrame(new.toarray(),columns=tfidf.get_feature_names_out())

In [11]:
df

    absolute    adding  allowing  audience  authenticity  ...    twists  visually    weaves   written      year
0   0.377964  0.000000  0.000000  0.000000      0.000000  ...  0.000000  0.000000  0.000000  0.000000  0.000000
1   0.000000  0.000000  0.000000  0.000000      0.000000  ...  0.000000  0.324869  0.000000  0.000000  0.000000
2   0.000000  0.000000  0.000000  0.000000      0.000000  ...  0.000000  0.000000  0.000000  0.000000  0.333333
3   0.000000  0.000000  0.000000  0.000000      0.000000  ...  0.000000  0.000000  0.000000  0.000000  0.000000
4   0.000000  0.000000  0.000000  0.000000      0.000000  ...  0.000000  0.000000  0.000000  0.000000  0.000000
5   0.000000  0.000000  0.000000  0.000000      0.324869  ...  0.000000  0.000000  0.000000  0.000000  0.000000
6   0.000000  0.000000  0.316228  0.316228      0.000000  ...  0.000000  0.000000  0.000000  0.000000  0.000000
7   0.000000  0.308973  0.000000  0.000000      0.000000  ...  0.000000  0.000000  0.000000  0.000000  0.000000
8   0.000000  0.000000  0.000000  0.000000      0.000000  ...  0.000000  0.000000  0.320461  0.000000  0.000000
9   0.000000  0.000000  0.000000  0.000000      0.000000  ...  0.333333  0.000000  0.000000  0.000000  0.000000
10  0.000000  0.000000  0.000000  0.000000      0.000000  ...  0.000000  0.000000  0.000000  0.301511  0.000000
11  0.000000  0.000000  0.000000  0.000000      0.000000  ...  0.000000  0.000000  0.000000  0.000000  0.000000

[12 rows x 111 columns]