In [30]:
import numpy as np
import pandas as pd
from sklearn.linear_model import LogisticRegression,LinearRegression,ElasticNet,Ridge
from sklearn.model_selection import KFold, cross_val_score,GridSearchCV
from sklearn.pipeline import Pipeline

In [31]:
conc=pd.read_csv('D:\\AshleshaRuchika\\PGCP-AI\\Machine Learning\\Concrete_Strength\\Concrete_Data.csv')
X,y=conc.drop('Strength',axis=1),conc['Strength']
lr=LinearRegression()
kfold=KFold(n_splits=5,shuffle=True,random_state=26)
results=cross_val_score(lr,X,y,cv=kfold)
print(results)
print(np.mean(results))

[0.61474372 0.56604898 0.59335131 0.61186382 0.62837728]
0.602877022245518

In [32]:
ridge=Ridge()
alphas=np.linspace(0.001,10,30)
scores=[]
for a in tqdm(alphas):
    ridge=Ridge(alpha=a)
    kfold=KFold(n_splits=5,shuffle=True,random_state=26)
    results=cross_val_score(ridge,X,y,cv=kfold)
    scores.append([a,np.mean(results)])
df_scores=pd.DataFrame(scores,columns=['alpha',"score"])
df_scores.sort_values("score",ascending=False)

100%|██████████████████████████████████████████████████████████████████████████████████| 30/30 [00:00<00:00, 32.05it/s]

        alpha     score
29  10.000000  0.602878
28   9.655207  0.602878
27   9.310414  0.602878
26   8.965621  0.602878
25   8.620828  0.602878
24   8.276034  0.602878
23   7.931241  0.602878
22   7.586448  0.602878
21   7.241655  0.602878
20   6.896862  0.602878
19   6.552069  0.602878
18   6.207276  0.602878
17   5.862483  0.602878
16   5.517690  0.602878
15   5.172897  0.602878
14   4.828103  0.602878
13   4.483310  0.602878
12   4.138517  0.602877
11   3.793724  0.602877
10   3.448931  0.602877
9    3.104138  0.602877
8    2.759345  0.602877
7    2.414552  0.602877
6    2.069759  0.602877
5    1.724966  0.602877
4    1.380172  0.602877
3    1.035379  0.602877
2    0.690586  0.602877
1    0.345793  0.602877
0    0.001000  0.602877

### Decision Tree

In [33]:
features=[2,3,4,5,6,7]
scores=[]
for f in features:
    rf=RandomForestRegressor(random_state=26,max_features=f)
    results=cross_val_score(rf,X,y,cv=kfold, scoring='neg_root_mean_squared_error')
    scores.append([f,np.mean(results)])
df_scores=pd.DataFrame(scores,columns=['features',"score"])
df_scores.sort_values("score",ascending=False)

   features     score
2         4 -4.751942
3         5 -4.754536
4         6 -4.790249
1         3 -4.794503
5         7 -4.814700
0         2 -5.088724

 ## Net Elasttic

In [34]:
alphas=np.linspace(0.001,10,30)
ratios=np.linspace(0.001,1,3)
scores=[]
for a in tqdm(alphas):
    for r in ratios:
        el=ElasticNet(alpha=a,l1_ratio=r)
        kfold=KFold(n_splits=5,shuffle=True,random_state=26)
        results=cross_val_score(el,X,y,cv=kfold)
        scores.append([a,r,np.mean(results)])
df_scores=pd.DataFrame(scores,columns=['alpha',"ratio","score"])
df_scores.sort_values("score",ascending=False)

100%|██████████████████████████████████████████████████████████████████████████████████| 30/30 [00:03<00:00,  9.67it/s]

        alpha  ratio     score
24   2.759345  0.001  0.602982
21   2.414552  0.001  0.602981
27   3.104138  0.001  0.602981
30   3.448931  0.001  0.602978
18   2.069759  0.001  0.602977
..        ...    ...       ...
77   8.620828  1.000  0.598389
80   8.965621  1.000  0.598299
83   9.310414  1.000  0.598207
86   9.655207  1.000  0.598110
89  10.000000  1.000  0.598010

[90 rows x 3 columns]

In [35]:
alphas=np.linspace(0.001,10,30)
ratios=np.linspace(0.001,1,3)
scores=[]
for a in tqdm(alphas):
    for r in ratios:
        el=ElasticNet(alpha=a,l1_ratio=r)
        kfold=KFold(n_splits=5,shuffle=True,random_state=26)
        results=cross_val_score(el,X,y,cv=kfold, scoring='neg_root_mean_squared_error')
        scores.append([a,r,np.mean(results)])
df_scores=pd.DataFrame(scores,columns=['alpha',"ratio","score"])
df_scores.sort_values("score",ascending=False)

100%|██████████████████████████████████████████████████████████████████████████████████| 30/30 [00:02<00:00, 11.50it/s]

        alpha  ratio      score
27   3.104138  0.001 -10.456384
30   3.448931  0.001 -10.456385
24   2.759345  0.001 -10.456410
33   3.793724  0.001 -10.456410
36   4.138517  0.001 -10.456456
..        ...    ...        ...
77   8.620828  1.000 -10.514769
80   8.965621  1.000 -10.515979
83   9.310414  1.000 -10.517215
86   9.655207  1.000 -10.518506
89  10.000000  1.000 -10.519846

[90 rows x 3 columns]

 ## using pipeline

In [37]:
features=[2,3,4,5,6,7]
scores=[]
for f in features:
    rf=RandomForestRegressor(random_state=26,max_features=f)
    pipe=Pipeline([("OHE",transf),("RF",rf)])
    results=cross_val_score(pipe,X,y,cv=kfold, scoring='neg_root_mean_squared_error')
    scores.append([f,np.mean(results)])
df_scores=pd.DataFrame(scores,columns=['features',"score"])
df_scores.sort_values("score",ascending=False)

   features     score
2         4 -4.751942
3         5 -4.754536
4         6 -4.790249
1         3 -4.794503
5         7 -4.814700
0         2 -5.088724

## housing Dataset

In [38]:
housing=pd.read_csv('D:\\AshleshaRuchika\\PGCP-AI\\Machine Learning\\Datasets\\Housing.csv')
housing

,price,lotsize,bedrooms,bathrms,stories,driveway,recroom,fullbase,gashw,airco,garagepl,prefarea
0,42000.0,5850,3,1,2,yes,no,yes,no,no,1,no
1,38500.0,4000,2,1,1,yes,no,no,no,no,0,no
2,49500.0,3060,3,1,1,yes,no,no,no,no,0,no
3,60500.0,6650,3,1,2,yes,yes,no,no,no,0,no
4,61000.0,6360,2,1,1,yes,no,no,no,no,0,no
...,...,...,...,...,...,...,...,...,...,...,...,...
541,91500.0,4800,3,2,4,yes,yes,no,no,yes,0,no
542,94000.0,6000,3,2,4,yes,no,no,no,yes,0,no
543,103000.0,6000,3,2,4,yes,yes,no,no,yes,1,no
544,105000.0,6000,3,2,2,yes,yes,no,no,yes,1,no
545,105000.0,6000,3,1,2,yes,no,no,no,yes,1,no

In [56]:
# X,y=housing.drop('price',axis=1),housing['price']
# ohe=OneHotEncoder(drop="first").set_output(transform="pandas")
# transf=ColumnTransformer(transformers=[("OHE",ohe, make_column_selector
#                                         (dtype_include=object))],remainder="passthrough",verbose_feature_names_out=False)
# features=[2,3,4,5,6,7]
# scores=[]
# for f in features:
#     rf=RandomForestRegressor(random_state=26,max_features=f)
#     pipe=Pipeline([("OHE",transf),("RF",rf)])
#     results=cross_val_score(pipe,X,y,cv=kfold, scoring='neg_root_mean_squared_error')
#     scores.append([f,np.mean(results)])
# df_scores=pd.DataFrame(scores,columns=['features',"score"])
# df_scores.sort_values("score",ascending=False)

kfold = KFold(n_splits=5, shuffle=True, random_state=26)

X, y = housing.drop('price', axis=1), housing['price']

# Corrected OneHotEncoder with sparse_output=False
ohe = OneHotEncoder(drop="first", sparse_output=False).set_output(transform="pandas")

transf = ColumnTransformer(
    transformers=[("OHE", ohe, make_column_selector(dtype_include=object))],
    remainder="passthrough",
    verbose_feature_names_out=False
)

features = [2, 3, 4, 5, 6, 7]
scores = []

for f in features:
    rf = RandomForestRegressor(random_state=26, max_features=f)
    pipe = Pipeline([("OHE", transf), ("RF", rf)])
    
    # This should now run without the ValueError
    results = cross_val_score(pipe, X, y, cv=kfold, scoring='neg_root_mean_squared_error')
    scores.append([f, np.mean(results)])

df_scores = pd.DataFrame(scores, columns=['features', "score"])
df_scores.sort_values("score", ascending=False)

   features         score
1         3 -16204.207742
0         2 -16284.461884
3         5 -16338.488053
2         4 -16530.071722
4         6 -16686.581621
5         7 -16759.855179

In [58]:
# alphas=np.linspace(0.001,10,30)
# params={'alpha':alphas}
# ridge=Ridge()
# gcv=GridSearchCV(estimator=ridge,param_grid=params,cv=kfold)
# gcv.fit(X, y)
# pd_cv=pd.DataFrame(gcv.cv_results_)
# pd_cv
alphas = np.linspace(0.001, 10, 30)
params = {'RIDGE__alpha': alphas} # Note the 'RIDGE__' prefix for the pipeline

# 2. Reuse your existing transformer (transf) from the previous step
ridge = Ridge()
pipe_ridge = Pipeline([("OHE", transf), ("RIDGE", ridge)])

# 3. Setup GridSearchCV with the pipeline
gcv = GridSearchCV(estimator=pipe_ridge, param_grid=params, cv=kfold, scoring='r2')
gcv.fit(X, y)

# 4. View results
pd_cv = pd.DataFrame(gcv.cv_results_)
pd_cv[['param_RIDGE__alpha', 'mean_test_score', 'rank_test_score']].sort_values('rank_test_score').head()

    param_RIDGE__alpha  mean_test_score  rank_test_score
13            4.483310         0.641760                1
12            4.138517         0.641757                2
14            4.828103         0.641754                3
11            3.793724         0.641747                4
15            5.172897         0.641742                5

In [59]:
gcv.best_params_,gcv.best_score_

({'RIDGE__alpha': np.float64(4.483310344827587)},
 np.float64(0.6417595524086313))

In [61]:
# params={'alpha':np.linspace(0.001,10,30),'l1_ratio':np.linspace(0.001,1,10)}
# el=ElasticNet()
# gcv=GridSearchCV(estimator=el,param_grid=params,cv=kfold)
# gcv.fit(X,y)
# gcv.best_params_,gcv.best_score_
el = ElasticNet()
pipe_el = Pipeline([("OHE", transf), ("EL", el)])

# 2. Update params with the "EL__" prefix
params = {
    'EL__alpha': np.linspace(0.001, 10, 30),
    'EL__l1_ratio': np.linspace(0.001, 1, 10)
}

# 3. Run GridSearchCV
gcv = GridSearchCV(estimator=pipe_el, param_grid=params, cv=kfold, scoring='r2')
gcv.fit(X, y)

print(f"Best Parameters: {gcv.best_params_}")
print(f"Best R2 Score: {gcv.best_score_}")

Best Parameters: {'EL__alpha': np.float64(0.001), 'EL__l1_ratio': np.float64(0.001)}
Best R2 Score: 0.6410935983796795

In [63]:
# features=[2,3,4,5,6,7]
# scores=[]
# for f in features:
#     rf=RandomForestRegressor(random_state=26,max_features=f)
#     results=cross_val_score(rf,X,y,cv=kfold, scoring='neg_root_mean_squared_error')
#     scores.append([f,np.mean(results)])
# df_scores=pd.DataFrame(scores,columns=['features',"score"])
# df_scores.sort_values("score",ascending=False)
features = [2, 3, 4, 5, 6, 7]
scores = []

for f in features:
    # 1. Re-initialize the model with the current f
    rf = RandomForestRegressor(random_state=26, max_features=f)
    
    # 2. Re-wrap it in the pipeline so it can handle the strings in X
    pipe = Pipeline([("OHE", transf), ("RF", rf)])
    
    # 3. Run cross-validation on the PIPE, not just the rf
    results = cross_val_score(pipe, X, y, cv=kfold, scoring='neg_root_mean_squared_error')
    
    scores.append([f, np.mean(results)])

df_scores = pd.DataFrame(scores, columns=['features', "score"])
df_scores.sort_values("score", ascending=False)

   features         score
1         3 -16204.207742
0         2 -16284.461884
3         5 -16338.488053
2         4 -16530.071722
4         6 -16686.581621
5         7 -16759.855179

In [64]:
# params={'max_features':[2,3,4,5,6,7]}
# rf=RandomForestRegressor(random_state=26)
# pipe=Pipeline([('OHE',transf),('RF',rf)])
# pipe.get_params()
from sklearn.model_selection import GridSearchCV

# Note the 'RF__' prefix to tell the pipeline to pass these to the RandomForest step
params = {'RF__max_features': [2, 3, 4, 5, 6, 7]}

rf = RandomForestRegressor(random_state=26)
pipe = Pipeline([('OHE', transf), ('RF', rf)])

# Now run the GridSearch
gcv = GridSearchCV(estimator=pipe, param_grid=params, cv=kfold, scoring='neg_root_mean_squared_error')
gcv.fit(X, y)

# Get the best results
print(f"Best Max Features: {gcv.best_params_}")
print(f"Best RMSE: {-gcv.best_score_}") # Negating to see the actual error value

Best Max Features: {'RF__max_features': 3}
Best RMSE: 16204.207742358189

In [65]:
# params={'RF__max_features':[2,3,4,5,6,7]}
# gcv=GridSearchCV(estimator=pipe,param_grid=params,cv=kfold,n_jobs=-1,scoring='neg_root_mean_squared_error')
# gcv.fit(X,y)
# gcv.best_params_,gcv.best_score_

params = {'RF__max_features': [2, 3, 4, 5, 6, 7]}
gcv = GridSearchCV(
    estimator=pipe, 
    param_grid=params, 
    cv=kfold, 
    n_jobs=-1, 
    scoring='neg_root_mean_squared_error'
)

# 5. Fit and Results
gcv.fit(X, y)
print(f"Best Parameters: {gcv.best_params_}")
print(f"Best RMSE: {-gcv.best_score_}")

Best Parameters: {'RF__max_features': 3}
Best RMSE: 16204.207742358189

In [66]:
## chemical process data

In [ ]:
# imp=SimpalInputer()
# rf=RandomForestRegressor(random_state=26)
# pipe=Pipeline([])